### ISSUE TITLE
TBI - project-access: Add support for multiple project types/artifacts

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#1007]
### Description
The current implementation of search functions in `@sap-ux/project-access` is restricted to Fiori elements and Fiori freestyle applications. There is also a demand to find extension projects, adaptation projects, and UI5 libraries/modules.

### Value
Central functionality to find different Fiori artifacts

### Architecture Elaboration
If we just add new functions to search for other Fiori artifacts, we might end up traversing the workspace multiple times. To avoid this, we should provide a find function that allows to collects multiple files, extensions, or folders. 

To classify `applications`, `adaptations`, `extensions`, and `libraries`, following criteria is used

| Artifact type | `manifest.json` | `['sap.app'].type` in manifest | `{approot}/.extconfig.json` | `manifest.appdescr_variant` |
| -- | :--: | :--: | :--: | :--: |
| Application | ✓ | `application` | ✗ | ✗ |
| Adaptation Project | ✗ | ✗ | ✗ | ✓ |
| Extension Project | ✓ | `application` | ✓ | ✗ |
| Library | ✓ | `library` | ✗ | ✗ |

### Tasks
- [ ] Provide function to search for multiple files, extensions, folders
- [ ] Provide functionality to search for Fiori artifacts

**Comment by tobiasqueck** [comment]
> {approot}/.adp/config.json

That is design time file from WebIDE. So, it is not required that it exists in every adaption project. I would check for a `manifest.appdescr_variant` in the root of the `webapp` which is as required for an adaptation project as the manifest is for an application.

**Comment by devinea** [comment]
> > {approot}/.adp/config.json
> 
> That is design time file from WebIDE. So, it is not required that it exists in every adaption project. I would check for a `manifest.appdescr_variant` in the root of the `webapp` which is as required for an adaptation project as the manifest is for an application.

`{approot}/.adp/config.json` is used in BAS and written during migration.
It looks the from the US https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/14968 that `.che/project.json` was the old name in WebIDE.
Since the `{approot}/.adp/config.json` is added during migration we know it is a project that is supported by Fiori tools and not an old project that has not been migrated yet. Using the `manifest.appdescr_variant` alone does not help distinguish a project we support or not. Also it is presumably faster to find from the `{approot}` than searching the webapp folder name and checking for `manifest.appdescr_variant` in it.

**Comment by tobiasqueck** [comment]
My response is based on the description. There it is stated that we check the `manifest.json` for type `application` to detect an app - nothing about the `sapux` flag, therefore, I would expect the same logic for adaptation projects.

> faster to find from the {approot} than searching the webapp
Well, same argument as before, we already do it for the `manifest.json`

**Comment by Klaus-Keller** [comment]
After discussions I've change the identifying file for adaptation projects to `manifest.appdescr_variant`. However, as the tools accept migrated adaptation projects only, there is an additional check for `{approot}/.adp/config.json` in the coding.

**Comment by Klaus-Keller** [comment]
New version of `@sap-ux/project-access` containing `findFioriArtifacts()` is available.
