### ISSUE TITLE
TBI - Remove eslint disables from the locate-reuse-libs.js

### ISSUE THREAD

**Issue by unseen1980** [SAP/open-ux-tools#1012]
### Description (include screenshots)
Remove the rules below
```/*eslint-disable fiori-custom/sap-browser-api-warning, fiori-custom/sap-no-dom-access*/```

Files under the test folder use different eslint ruleset

### Tasks
- [ ] Task 1

**Comment by tobiasqueck** [comment]
Adding this as a sub-task to https://github.com/SAP/open-ux-tools/issues/969
