### ISSUE TITLE
dependabot only creates PR's to update dependencies in the root package.json

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#102]
### **Bug Description**
dependabot only creates PR's to update dependencies in the root package.json
Per https://github.com/SAP/open-ux-tools/blob/main/.github/dependabot.yml#L9

### **Expected Behavior**
dependabot should create PR's to update dependencies in the all module package.json's

### **Steps to Reproduce**
n/a

### **Context**
n/a

### **Log Output / Stack Trace / Screenshots**
n/a

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by aditirao7** [comment]
Hi! Can I take up this issue?

**Comment by tobiasqueck** [comment]
@kranthie-sap @devinea what is the state of this one?

**Comment by kranthie-sap** [comment]
@tobiasqueck: This is being worked on in this PR - https://github.com/SAP/open-ux-tools/pull/951
I just worked on the review comments and will hopefully merge this soon.

**Comment by kranthie-sap** [comment]
Renovate (replacement for dependabot) has been configured and merged using PR #951.
