### ISSUE TITLE
BUG - Odata V4 int-test OPA tests not passing when generateIndex is set to false

### ISSUE THREAD

**Issue by unseen1980** [SAP/open-ux-tools#1071]
### Description
Odata V4 int-test OPA tests not passing when generateIndex is set to false

### Expected results
Opa should use the flpSandbox.html when generateIndex is set to false

### Actual results
![image](https://github.com/SAP/open-ux-tools/assets/2386570/efad9661-0df3-4a97-b728-6ab172b43db0)

**Comment by devinea** [comment]
@unseen1980 OK to close this now?

**Comment by tobiasqueck** [comment]
@unseen1980 OK to close this now?

**Comment by unseen1980** [comment]
This can be closed, thank you. 👍
