### ISSUE TITLE
BUG - Using the ui5-proxy-middleware did not work as expected

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1073]
### Related Feature
Feature request: _issue number_

### Description
I wanted to use the `ui5-proxy-middleware` programmatically but it did not work as expected.
In my setup I only want to add the middleware if specific conditions are given, so I cannot define it in the `ui5.yaml` directly. I tried to proxy the calls to three specific lib with 
```typescript
router.use(ui5Proxy({ path: "/resources/sap/ca/ui", url: "https://ui5.sap.com/"}));
router.use(ui5Proxy({ path: "/resources/sap/ui/generic", url: "https://ui5.sap.com/"}));
router.use(ui5Proxy({ path: "/resources/sap/suite/ui/generic", url: "https://ui5.sap.com/"}));
```
however the result was that all requests got intercepted.

I could fix it by changing the code to
```typescript
router.use("/resources/sap/ca/ui", ui5Proxy({ path: "/", url: "https://ui5.sap.com"}));
router.use("/resources/sap/ui/generic", ui5Proxy({ path: "/", url: "https://ui5.sap.com"}));
router.use("/resources/sap/suite/ui/generic", ui5Proxy({ path: "/", url: "https://ui5.sap.com"}));
```
However that did not meet my expectations.

Is this a bug or are my expectations wrong?

### Steps to Reproduce
See description

### Expected results
See description

### Actual results
See description

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
@zdravko-georgiev do you have an opinion?

**Comment by zdravko-georgiev** [comment]
@tobiasqueck If I understand this https://expressjs.com/en/4x/api.html#router.use correctly, then I fear that your expectations are wrong. Registering the middleware like:

```
router.use(ui5Proxy({ path: "/resources/sap/ca/ui", url: "https://ui5.sap.com/"}));
```
Will trigger the `ui5Proxy` middleware for every requests regardless of the `path` configuration of the `ui5Proxy` middleware.

**Comment by tobiasqueck** [comment]
@zdravko-georgiev should we enhance the example at the end of https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-proxy-middleware/README.md to prevent future misunderstandings?

**Comment by zdravko-georgiev** [comment]
Yes, it make sense.
