### ISSUE TITLE
BUG - Archiving a project includes `.git` folder

### ISSUE THREAD

**Issue by johannes-kolbe** [SAP/open-ux-tools#1087]
### Related Feature
Feature request: _issue number_

### Description
Archiving a project includes the `.git` folder, if existing. 
This should be excluded from the archive. It can increase the file size dramatically.

### Steps to Reproduce
1. Clone or initiate a git-based project, e.g. `https://github.com/SAP-samples/cap-sflight.git` 
2. For convenience, use the command `Fiori: Archive Project` in BAS/VSCode
3. Unzip project in explorer
4. Enable hidden files view, see that `.git` folder is included (in this case ~8mb)

### Expected results
- No `.git` folder existing

### Actual results
- `.git` folder included

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by johannes-kolbe** [comment]
@Klaus-Keller - Oh thanks for investigating already, had the same place in mind. Would you mind having a look at #1088? Added case for non-existing `gitignore` file too.

**Comment by Klaus-Keller** [comment]
> @Klaus-Keller - Oh thanks for investigating already, had the same place in mind. Would you mind having a look at #1088? Added case for non-existing `gitignore` file too.

Good point, although a git repo without `.gitignore` is unlikely, it is possible and we should ignore `.git` in both cases.

**Comment by johannes-kolbe** [comment]
Done with #1088
