### ISSUE TITLE
@sap-ux/types as published npm package

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/open-ux-tools#1114]
Hi! I'd like to use types from @sap-ux/types subpackage on npm.

Could you please publish them too?

Thanks!

**Comment by ThePlenkov** [comment]
to make it even more clear:

Here is the type I'd like to use in my app:

https://sourcegraph.com/search?q=context%3Aglobal+MiddlewareParameters%3CC%3E+&patternType=standard&sm=1&groupBy=repo

**Comment by tobiasqueck** [comment]
@ThePlenkov these types shouldn't be published from here, they are only temporarily here, it should come from the UI5 tooling. I have already requested it at https://github.com/SAP/ui5-tooling/issues/651. Maybe you could add your voice of interest there as well.
