### ISSUE TITLE
TBI - Add utility function to project-access module to detect mta folder path

### ISSUE THREAD

**Issue by slin-sap** [SAP/open-ux-tools#1126]
### Description (include screenshots)
Managed MTA (multi-target application) has the mta configuration in an app router folder. This folder can contain multiple Fiori apps, and allow bundling and deploy of multiple Fiori apps together.

### Value
It is useful to provide a utility function in project-access, which can look up the parent folder chain to find the app router folder path from a given Fiori app. 

### Architecture Elaboration
Does it requires architecture elaboration?
Discussed with @Klaus-Keller. Please comment on this.

### Tasks
- [x] Migrate the utility function
- [x] Unit tests

**Comment by tobiasqueck** [comment]
@slin-sap is this completed with https://github.com/SAP/open-ux-tools/pull/1130?

**Comment by Klaus-Keller** [comment]
Yes, functionality is in `main` branch, closing this ticket.
