### ISSUE TITLE
BUG - blocked from deploying to onprem target system; similar to #1128

### ISSUE THREAD

**Issue by ulr1chA** [SAP/open-ux-tools#1148]
### Description
Hi,

the parameter --noConfig seems to have an impact on the credentials within fiori deploy.
The result is always -> info  transportRequestUploadCTS - Request failed with status code 401
If we use a specific version (@sap/ux-ui5-tooling@1.9.4) the issue doesn't appear.

Unsuccessful deployment:
fiori deploy --failfast --yes --username ABAP_USER --password ABAP_PASSWORD --description "TEST" **--noConfig** --url https://xxxxx.xxxxx.xxx --client 100 --transport xxxxxxx --package xxxxxxxxx --name xxxxxxxxxx

Successful deployment:
fiori deploy --failfast --yes --username ABAP_USER --password ABAP_PASSWORD --description "TEST" **--config "ui5-deploy.yaml"** https://xxxxx.xxxxx.xxx --client 100 --transport xxxxxxx --package xxxxxxxxx --name xxxxxxxxxx
info  transportRequestUploadCTS - info abap-deploy-task /xxxx/XXXXX Creating archive with UI5 build result.
info  transportRequestUploadCTS - info abap-deploy-task /xxxx/XXXXX Archive created.
info  transportRequestUploadCTS - info abap-deploy-task /xxxx/XXXXX Starting to deploy.
info  transportRequestUploadCTS - info abap-deploy-task /xxxx/XXXXX /xxxx/XXXXX found on target system: true
info  transportRequestUploadCTS - info abap-deploy-task /xxxx/XXXXX Application /xxxx/XXXXX has been uploaded and registered successfully

### Actual results
fiori deploy --failfast --yes --username ABAP_USER --password ABAP_PASSWORD --description "TEST" **--noConfig** --url https://xxxxx.xxxxx.xxx --client 100 --transport xxxxxxx --package xxxxxxxxx --name xxxxxxxxxx
info  transportRequestUploadCTS - 2023-08-08 06:57:55 info    abap-deploy-task: Creating archive from dist. 
info  transportRequestUploadCTS - 2023-08-08 06:57:55 info    abap-deploy-task: Archive created from dist. 
info  transportRequestUploadCTS - 2023-08-08 06:57:55 info    abap-deploy-task: Starting to deploy. 
info  transportRequestUploadCTS - 2023-08-08 06:57:55 error   abap-deploy-task: Deployment has failed. 
info  transportRequestUploadCTS - 2023-08-08 06:57:55 error   abap-deploy-task: Change logging level to debug your issue
info  transportRequestUploadCTS - 	(see examples https://github.com/SAP/open-ux-tools/tree/main/packages/deploy-tooling#configuration-with-logging-enabled) 
info  transportRequestUploadCTS - Request failed with status code 401

Related issue: #1128

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
@cianmSAP @longieirl could you please have a look?

**Comment by longieirl** [comment]
@ulr1chA can you ensure there is no `.env` file present in your project that is being picked up?

**Comment by longieirl** [comment]
Thank you. Let me re-create the issue and I will get back to you asap.

**Comment by longieirl** [comment]
@ulr1chA not sure what version of ui5-tooling you are using but with the latest version 1.10.4 the command is working.

I created a new dev space, geneated a Fiori LROP UI app with using an ABAP deployment configuration and ran the following command;

```
fiori deploy --failfast --yes --username MyUsername --password MyPassword --description 'TEST' --noConfig --url $H2O_URL/destinations/BTPDestintion --client 000 --package '$tmp' --name JLE2EAUG
````
This setup used 1.10.4 version of ui5-tooling.

You can also use an .env file as follows if you like;

```
XYZ_USER=MyUsername
XYZ_PASSWORD=MyPassword
```
```
fiori deploy --failfast --yes --username env:XYZ_USER --password env:XYZ_PASSWORD --description 'TEST' --noConfig --url $H2O_URL/destinations/UIA --client 000 --package '$tmp' --name JLE2EAUG
````

If this does not work for you, please upload your package-lock.json file.
John

**Comment by longieirl** [comment]
@ulr1chA another CLI param you can add is --verbose, for exmaple;
```
fiori deploy --failfast --yes --username MyUsername --password MyPassword --description 'TEST' --noConfig --url $H2O_URL/destinations/BTPDestintion --client 000 --package '$tmp' --name JLE2EAUG --noConfig --verbose
```
This will show the configuration used under the hood, you can append that as well to the ticket, just obsecure any sensitive values!

**Comment by ulr1chA** [comment]
Call with noConfig:
setup:
/data/tools/node/18.12.1/x64/lib
├── @sap/ux-ui5-tooling@1.10.4
├── @ui5/cli@3.3.4
├── @ui5/fs@3.0.4
├── @ui5/logger@3.0.0
├── corepack@0.14.2
└── npm@8.19.2
fiori call:
` fiori deploy --failfast --yes --noConfig --username "ABAP_USER" --password "ABAP_PASSWORD" --description "$(xxx)" --url "$(URL)" --client "$(CLIENT)" --transport "$(xxxx)" --package "$(xxx)" --name "$(xxx)" --verbose yes`
Result: 401
`2023-08-09 08:25:38 debug   abap-deploy-task: {
  app: {
    name: '/xxxx/xxxxx',
    description: 'xxxxxx',
    package: '/xxxx/xxx',
    transport: 'xxxxxx'
  },
  target: {
    url: 'xxxxxxxx'
    client: '100',
    cloud: undefined,
    destination: undefined,
    serviceKey: undefined,
    params: undefined,
    service: undefined
  },
  credentials: 'hidden',  
  test: undefined,
  safe: undefined,
  keep: undefined,
  strictSsl: true,
  yes: true,
  createTransport: undefined,
  retry: false
}`

call without noConfig
setup:
/data/tools/node/18.12.1/x64/lib
├── @sap/ux-ui5-tooling@1.10.4
├── @ui5/cli@3.3.4
├── @ui5/fs@3.0.4
├── @ui5/logger@3.0.0
├── corepack@0.14.2
└── npm@8.19.2
fiori call:
`fiori deploy --failfast --yes --username "ABAP_USER" --password "ABAP_PASSWORD" --description "$(xxxx)" --url "$(URL)" --client "$(xxxx)" --transport "$(xxxxx)" --package "$(xxxxxx)" --name "$(xxxxxx)" --verbose yes`
result:
`debug abap-deploy-task /BASF/QM_SRREC   target: {
debug abap-deploy-task /BASF/QM_SRREC     destination: 'xxxxxx',
debug abap-deploy-task /BASF/QM_SRREC     url: 'xxxxxxx',
debug abap-deploy-task /BASF/QM_SRREC     client: '100'
debug abap-deploy-task /BASF/QM_SRREC   },
debug abap-deploy-task /BASF/QM_SRREC   app: {
debug abap-deploy-task /BASF/QM_SRREC     name: '/xxxx/xxxxx',
debug abap-deploy-task /BASF/QM_SRREC     description: 'xxxx',
debug abap-deploy-task /BASF/QM_SRREC     package: '/xxx/xxxxx,
debug abap-deploy-task /BASF/QM_SRREC     transport: 'xxxxxx'
debug abap-deploy-task /BASF/QM_SRREC   },
debug abap-deploy-task /BASF/QM_SRREC   credentials: undefined,
debug abap-deploy-task /BASF/QM_SRREC   yes: true,
debug abap-deploy-task /BASF/QM_SRREC   ignoreCertError: false,
debug abap-deploy-task /BASF/QM_SRREC   strictSsl: true,
debug abap-deploy-task /BASF/QM_SRREC   configPath: 'ui5-deploy.yaml',
debug abap-deploy-task /BASF/QM_SRREC   testMode: false,
debug abap-deploy-task /BASF/QM_SRREC   log: 5,
debug abap-deploy-task /BASF/QM_SRREC   retry: true,
debug abap-deploy-task /BASF/QM_SRREC   test: false,
debug abap-deploy-task /BASF/QM_SRREC   safe: true,
debug abap-deploy-task /BASF/QM_SRREC   keep: true,
debug abap-deploy-task /BASF/QM_SRREC   cli: false
`
[package-lock.txt](https://github.com/SAP/open-ux-tools/files/12300094/package-lock.txt)

**Comment by longieirl** [comment]
Hi,
Couple of things to confirm;
1. Are you running these scripts on BAS?
2. The call using the ui5-deploy config, is passing a destination, can please supply the `Authentication` used in the destination properties?
3. The `destination` CLI param is missing from failing script? Is this expected?

From what I can see from the debug calls, the script works when pointing to a destination but fails when hitting the URL directly?

John

**Comment by ulr1chA** [comment]
Hi John,

I did some tests with the different versions of ux-ui5-tooling and it seems that issue comes with 1.10.3.
/data/tools/node/18.12.1/x64/lib
├── @sap/ux-ui5-tooling@1.10.3
├── @ui5/cli@3.4.0
├── @ui5/fs@3.0.4
├── @ui5/logger@3.0.0
├── corepack@0.14.2
└── npm@8.19.2

The result is:
error: unknown option '--username'
##[error]Bash exited with code '1'.

With 1.10.4 the 401 issue appears.

**Comment by longieirl** [comment]
@ulr1chA can you reach out to me via my git profile, I would like to have a followup conversation with you to get a better understanding of your issue. What is throwing me is the title, `blocked from deploying to onprem target system` which indicates you are trying to deploy to an onPremise system which is accessible through a cloud connector setup. This type of setup would normally the endpoint URL is not publicly accessible.

**Comment by longieirl** [comment]
@ulr1chA thanks for reaching out, issue was unblocked by appending env to the username i.e. `env:ABAP_USER`. I will take a deeper look to understand why or how this worked previously without this where the credentials were replaced by environment variables.

**Comment by longieirl** [comment]
The next release of ui5-tooling will have a fix so that `env:` does not need to be appended to the crendentials from the CLI.

**Comment by longieirl** [comment]
Closing the issue as the fix was released, I've validated locally and it works.
