### ISSUE TITLE
TBI - Add LocalStorageConnector to html files for preview to keep personalizations across preview sessions

### ISSUE THREAD

**Issue by unseen1980** [SAP/open-ux-tools#1158]
When previewing apps in WebIDE personalization settings of the developer where persisted across browser refresh and preview sessions using the ~~sessionStorageConnector~~ LocalStorageConnector and storage in browser. This feature was and is not enabled in SAP Fiori apps generated with SAP Fiori tools. When refreshing the browser window all personalizations are resetted, which is inconvenient.

### Scope:

add {"connector":"~~SessionStorageConnector~~ LocalStorageConnector"} to the data-sap-ui-flexibilityServices bootstrap settings in flpSandbox.html files for preview on generation - this is only for preview not for productive delivery
Value

### Value
Feature parity with WebIDE.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by tobiasqueck** [comment]
In addition to the writers, please apply the fix as well at https://github.com/SAP/open-ux-tools/blob/main/packages/preview-middleware/templates/flp/sandbox.html.

**Comment by unseen1980** [comment]
Flexibility colleagues adviced that the SessionStorageConnector is the wrong connector. We should use LocalStorageConnector. @zdravko-georgiev

**Comment by zdravko-georgiev** [comment]
Done
