### ISSUE TITLE
TBI - Can not deploy ts-files to onpremise abap system for debugging

### ISSUE THREAD

**Issue by Kasde96** [SAP/open-ux-tools#1162]
I want to deploy my ts files of my sapui5 type script project to the s4 onpremise system. In the console after deployment I get the following errors: 
![image](https://github.com/SAP/ui5-typescript/assets/97966330/f4a69914-9f09-4057-888b-7ad8ad2efc1b)

I have added the following regex in the .UI5RepositoryTextFiles:  "^.*.ts$"

The reason I want to deploy my ts files is that I want to debug a specific development that only works in a Fiori Launchpad, so I want to debug my ts files and not the generic js files implemented with Babel. 

Can you please help me?

Thanks

**Comment by petermuessig** [comment]
Hi colleagues, can you please help @Kasde96 to answer the question how also `.ts` files can be deployed to ABAP? Is this possible at all or is there a limitation in the ABAP BSP repository?

**Comment by tobiasqueck** [comment]
> Is this possible at all or is there a limitation in the ABAP BSP repository?

@petermuessig @Kasde96 my understanding is that this is a limitation of the SAPUI5 ABAP repository service. Let's ask an expert @MatthiasSchmalz @silkearians to be sure.

**Comment by MatthiasSchmalz** [comment]
I think there is a typo in the filename of the config file. It must be  
.Ui5RepositoryTextFiles (second char is lowercase)

Unfortunately there have been some locations which specified the wrong name. We have corrected them but maybe we have missed one.

**Comment by Kasde96** [comment]
Thanks for pointing that out, I fixed the typo. The deployment is working fine now. Unfortunately, I still have the problem that I can't see the TS files in launchpad debug mode. 
Here is the source tab in the chrome development console:
![image](https://github.com/SAP/open-ux-tools/assets/97966330/58997fa1-4d1c-4ecb-b3f6-1d390949e616)

And the BSP application deployed in the onprem system:
![image](https://github.com/SAP/open-ux-tools/assets/97966330/4c1b6fa3-aa71-42c3-9be8-f143c52af72a)

Why don't I see the TS files in debug mode?

Thanks

**Comment by MatthiasSchmalz** [comment]
At least all the files are there. However the problem might be that you are actually running the Component-preload.js, which does not have a ts file.  
Maybe you have to disable the usage of the preload with xx-componentPreload=off (but don't use debug mode as this would then use the -dbg files).

**Comment by Kasde96** [comment]
After setting the url parameter sap-ui-xx-componentPreload=off the Component.js is loaded. Also i dont use the debug mode. But the TS-Files are not shown.
![image](https://github.com/SAP/open-ux-tools/assets/97966330/256c1f22-349b-4425-99a7-d5149ff3b162)

**Comment by MatthiasSchmalz** [comment]
@petermuessig do you have further ideas? At least all files are in the repo now.

**Comment by petermuessig** [comment]
@Kasde96 can you share your `package.json` > `dependencies` you are using? Maybe the version of the `ui5-tooling-transpile` is too old? And: do you have a custom `.babelrc`?

**Comment by Kasde96** [comment]
package.json:
![image](https://github.com/SAP/open-ux-tools/assets/97966330/8835f3e0-c3e6-48d6-8828-9679573b3944)

.babelrc
![image](https://github.com/SAP/open-ux-tools/assets/97966330/ebd79942-cc5a-4df8-81b8-6557d835df7b)

If i look in the BSP-Application on the onprem system the files are deployed
![image](https://github.com/SAP/open-ux-tools/assets/97966330/2b57a6bc-29d1-4402-89da-0f858be0d0b9)

Also in the dist folder in the sapui5 application the ts-files transpiled
![image](https://github.com/SAP/open-ux-tools/assets/97966330/d215f890-b44b-4e18-bf28-779be43c69a0)

But they are never loaded in the fiori launchpad

**Comment by petermuessig** [comment]
Oh, the `ui5-tooling-transpile` and all other dependencies are quite old. For a quick check, can you please just upgrade this dependency to `0.7.20` => https://www.npmjs.com/package/ui5-tooling-transpile/v/0.7.20? Several fixes have been done for in that direction since ^0.2.0. I don't know whether this version is properly used as the 0.x versions have a different meaning of  `^` than >=1.x versions.

**Comment by Kasde96** [comment]
I have updated all dependencies, it looks a bit better now. It has now generated -dbg.js files for me and I can now also use the debug mode normally. Unfortunately the TS files are still not loaded. Can it also be somehow that they are simply not loaded? They are available in the system.

**Comment by Kasde96** [comment]
I just noticed that in the js.map file the dbg.*.js files are specified as "sources", shouldn't the name of the TS file be there? Is this maybe also a problem or does it not matter in this case? 
![image](https://github.com/SAP/open-ux-tools/assets/97966330/72ad5f17-97d0-4912-835e-a201e3da8fd6)

**Comment by petermuessig** [comment]
The TypeScript files are referenced by the source maps AFAIR. In the debugger, when source maps are loaded you should see the `.ts` file, like shown here (it's from the UI5 ecosystem project):

<img width="1073" alt="image" src="https://github.com/SAP/open-ux-tools/assets/1589419/2bd66beb-1890-4928-b1bf-80e341abb66b">

BTW: maybe there is some wrong order in the `ui5.yaml`?

**Comment by Kasde96** [comment]
I just created a new TS app with the yoeman yo easy-ui5 ts-app generator and also there it is, when I transpile/build the files, that in the js.map under sources is the debug.js file. What does the ui5.yaml and package.json look like in your project. Do you have any special settings?

That's the project i created:
[com.myorg.myapp.zip](https://github.com/SAP/open-ux-tools/files/12317396/com.myorg.myapp.zip)

**Comment by petermuessig** [comment]
Good catch! There seems to be a bug (maybe more a side-effect) when the `minify` task of the UI5 Tooling is running. When you run the following command: 

```sh
npm run build -- --exclude-task minify
```

You should not see the `.ts` file. I think this should be an issue in the: https://github.com/ui5-community/ui5-ecosystem-showcase => can you open a ticket there and refer to this one? Then we can follow-up there. Thanks...
