### ISSUE TITLE
BUG - Invalid manifest datasource key created

### ISSUE THREAD

**Issue by unseen1980** [SAP/open-ux-tools#1248]
### Description

The generator is using the datasource as a key name in the manifest.  In some cases this leads to an invalid property name, if the datasource contains forward slashes.

### Steps to Reproduce
1. Generate a Fiori elements application on BAS using E.g. Y05 with data source `/DMO/UI_FLIGHT_R_V2_VAN`
2. Open the generated `manifest.json` file.
3. Navigate the `dataSources` section.
4. Observe the error.

### Expected results

The dataSource key name is valid.

### Actual results

The data source key name is not valid, see https://github.com/SAP/ui5-manifest/blob/master/schema.json#L349 for the valid regex.

**Comment by tobiasqueck** [comment]
@unseen1980 has this been fixed with the referenced PRs or is it still open?

**Comment by unseen1980** [comment]
Completed
