### ISSUE TITLE
BUG - Wrong link to error message displayed during deployment in BAS

### ISSUE THREAD

**Issue by mikicvi-SAP** [SAP/open-ux-tools#1257]
### Related Feature
Feature request: _issue number_

### Description
When deployment fails a link is displayed in the console, where more information about the deployment error can be found. But if deployment is done in BAS, then the link is using the virtual host from the destination, instead of the real host to the backend, e.g. link uses `http://esmclnt200:443`, where actually `https://ldciesm.abc.ade.domain:44300`should be used instead.

### Steps to Reproduce
Please check BCP issue 2280202476 

### Expected results
Working link is displayed in the console

### Actual results
Not working link is displayed in the console

### OS/Browser/Environment
OS:                      
- [x] Mac OS
- [x] Windows

Browser: 
- [x] Chrome
- [ ] Firefox
- [ ] Edge

Environment: 
- [x] Master
- [ ] Staging
- [ ] Production

--- 
### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue was missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by longieirl** [comment]
Validated with latest release, working as expected.
