### ISSUE TITLE
TBI - Export Node Checker Function

### ISSUE THREAD

**Issue by korotkovao** [SAP/open-ux-tools#1259]
### Description
Export the node checker function [getProcessVersions(logger?: ILogger): Promise<NodeJS.ProcessVersions>](https://github.com/SAP/open-ux-tools/blob/450925a4a359730e92aae1631628770b98832a52/packages/environment-check/src/checks/get-installed.ts#L200), so it could also be used outside this repository. 

### Value
Reduce code duplication in other modules

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by tobiasqueck** [comment]
@korotkovao has this been fixed with the referenced PR or is there still something open?

**Comment by korotkovao** [comment]
@tobiasqueck yes, this has been fixed and this issue can be closed now.
