### ISSUE TITLE
BUG - @sap-ux/create

### ISSUE THREAD

**Issue by 3lodey** [SAP/open-ux-tools#1310]
### Description
In @sap-ux/create dependencies is "@sap-ux/mockserver-config-writer": "0.1.10", but max version only "0.1.9"

### Steps to Reproduce
1.  npm i @sap-ux/create
2. See error

### Screenshots
![image](https://github.com/SAP/open-ux-tools/assets/13786960/30b6447b-ad7c-44fc-9466-9e5ca2078929)
![image](https://github.com/SAP/open-ux-tools/assets/13786960/360b309f-4452-4b22-ad0b-7e2162f0ef55)

**Comment by tobiasqueck** [comment]
@kranthie-sap any idea what went wrong with the publishing to npmjs? https://github.com/SAP/open-ux-tools/blob/main/packages/mockserver-config-writer/package.json shows version `0.1.10`.

**Comment by devinea** [comment]
I created a PR.

**Comment by kranthie-sap** [comment]
Thanks, @devinea.

**Comment by 3lodey** [comment]
@devinea Everything is working now, thank you very much!

**Comment by devinea** [comment]
Great. Thanks @3lodey
