### ISSUE TITLE
TBI - Improve interaction between multi-select dropdown and dialog buttons

### ISSUE THREAD

**Issue by gpeuc** [SAP/open-ux-tools#1317]
[As reported by users (VPN link)](https://support.wdf.sap.corp/sap(bD1lbiZjPTAwMSZkPW1pbiZpPTE=)/bc/bsp/sap/crm_ui_start/default.htm?saprole=ZCSSINTPROCE&crm-object-type=CRM_SRQM_INCIDENT&crm-object-keyname=OBJECT_GUID&crm-object-value=0090FAE68C701EDE91AA8C09DE903C84), there's a UX glitch when in a dialog we open a multi-select dropdown. It conceals the action buttons of the dialog, and forces users to click somewhere outside to first close the dropdown, and only then can they click `Add` `Cancel` buttons. This problem doesn't appear in regular dropdowns because as soon as we select something in them, they close. 

<img width="583" alt="Screenshot 2023-09-21 at 13 07 46" src="https://github.com/SAP/open-ux-tools/assets/44162846/42e69be9-1d44-426a-9239-79e6208e1eb3">

- - - - - -

I had a conversation with @815are and we will try two things.

Step zero: we need to do this magic only when the multi-select dialog is right above the buttons. If this dialog appears elsewhere above the buttons users can keep clicking or at least reach the buttons. At the moment the plan is to detect when it's positioned as the last element in a stack (or if it's the only element), right above the buttons.

**First:** we will try to animate growth of the dialog so it can shows buttons below the dropdown part. Something like this:

<img width="553" alt="Screenshot 2023-09-21 at 13 12 41" src="https://github.com/SAP/open-ux-tools/assets/44162846/40bb4294-ab3d-44f7-ad90-95f07774c357">

**Second:** if this feels strange (we have to test it and see how it feels), we will have to open the dropdown upwards. We already do this if the dialog is close to the bottom of the viewport (small screens). Like this:

<img width="653" alt="Screenshot 2023-09-21 at 13 13 45" src="https://github.com/SAP/open-ux-tools/assets/44162846/03eabe4f-8e3b-4461-94ec-97502ebc9879">

**Comment by hitesh-parmar** [comment]
@gpeuc I was thinking of having additional `Ok` and `Cancel` buttons as a part of the dropdown. Something like this 
https://mdbootstrap.com/docs/standard/extended/multiselect/

Only in this case it of c,ourse means 2 clicks for the user, but I still like it.
In all other cases, (i.e. when multi select comboxbox is not inside a modal popup) it will still be one click.

![Screenshot 2023-10-05 at 15 35 49](https://github.com/SAP/open-ux-tools/assets/24454497/400d1290-27c7-4d44-80a7-c4e98f3caa64)

**Comment by hitesh-parmar** [comment]
FYI..just saw the demo of the proposed solution - this also looks very good 👍

**Comment by gpeuc** [comment]
@hitesh-parmar yeah, we were thinking to add something into the dropdown itself, but it creates too many additional issues (like needing to click one more time to confirm). I think the expanding dialog hack works, let's see what the users will say.

**Comment by hitesh-parmar** [comment]
Hi @gpeuc, The additional click is only in one case i.e. when the dropdown is used inside a modal popup (and is the only one).
In all other cases, having an `Ok` and `Cancel` in the dropdown is beneficial.

> Only in this case it of c,ourse means 2 clicks for the user, but I still like it.
> In all other cases, (i.e. when multi select comboxbox is not inside a modal popup) it will still be one click.

**Comment by gpeuc** [comment]
@hitesh-parmar this adds inconsistency in component behaviour. Users can't really decrypt our internal logic when the button appears inside the dropdown, and when it doesn't. We know it, but it's too much work for the users to think about our mystical rules.

**Comment by cfg74** [comment]
Hi @hitesh-parmar @gpeuc as discussed in our call, the decision is to go with the proposal to expand / collapse the popup when the dropdown is opened, with minimizing flicker and covering edge cases (open to top on bottom border).

**Comment by 815are** [comment]
PR with solution #1323

**Comment by 815are** [comment]
@gpeuc 

Changes are merged. Can we close issue?
