### ISSUE TITLE
TBI - Provide functionality to return effective YAML configuration for preview middleware

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#1335]
### Description
Some SAP Fiori tools, like the run configuration editor,  need to know available endpoints (virtual and materialized HTML files) for application preview. This information is available in the `@sap-ux/preview-middleware`. The middleware should provide a function, to export the effective configuration as object, so consumers can read it.

### Value
Create possibility to build tools for preview.

### Architecture Elaboration
No

### Tasks
- [ ] Add the function
- [ ] Unit tests

**Comment by tobiasqueck** [comment]
@Klaus-Keller could you explain your use case? I think, I remember, it is needed for the "eject" functionality, to write the virtually hosted html files to the file system. If that is the case, wouldn't it be better if we provide a function that returns a map between fs path and the generated files?
Something along the lines:
```ts
generatePreviewFiles(ui5YamlPath: string) : Record<string, string>
```

**Comment by Klaus-Keller** [comment]
@tobiasqueck, it is required to be able to create run configurations which point to virtually hosted files.

**Comment by Klaus-Keller** [comment]
Feature has been merged, thanks @tobiasqueck.
