### ISSUE TITLE
FEATURE - Provide commonly used details about given project/app

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#1364]
### Description

Currently project access provides very limited information about the artifacts in the projects and tools would need to extract the more specific information themselves. In order to avoid duplicating such code, project access should provide a high level data structure which contains details about given project required by tools e.g available apps, services, annotations, i18n files etc. It should be in a format that is easily reusable across various tools.

### Technical Design
_What modules need to be created or enhanced?_ 
`@sap-ux/project-access`

_How would the functionality be exposed and how can it be consumed?_
A function that can be called for a given project/app root and which returns a data structure containing details about the given project/app.

Required information:
- root of the project
- apps
- services defined in manifest.json
  - metadata file service
  - annotation files for service (indicate which are local annotation files)

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a ...
**when** I execute ...
**then** ... will happen.

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by Klaus-Keller** [comment]
@voicis, code is merged with PR https://github.com/SAP/open-ux-tools/pull/1613. Closing this, feel free to reopen if something is missing.
