### ISSUE TITLE
BUG - Deployment successful although error displayed

### ISSUE THREAD

**Issue by marianfoo** [SAP/open-ux-tools#1369]
### Description
We use the open source component [Spreadsheet Importer.]( https://github.com/marianfoo/ui5-cc-spreadsheetimporter) We do not have the component deployed in the system, but use `resourceRoots` to use it only in the app itself.
During deployment we get an error that the component was not found in the system and the deployment failed.  
However, the deployment was successful and the component can be used normally.

> We _think_ we did not have this error with S/4HANA 2021, but not 100% sure.

Same error on ABAP Trial Platform 1909

### Steps to Reproduce
1. Implement a component without deployment in an UI5 App ( described like [here](https://docs.spreadsheet-importer.com/pages/GettingStarted/#setup-decentralized-deployment))
2. run deploy with `deploy-to-abap`

### Expected results
Successfull Deployment without error

### Actual results
Successfull Deployment with error:  
`error abap-deploy-task Z_********* In Anwendung Z_********* verwendete SAPUI5-Bibliothek/Kompon. cc.spreadsheetimporter.v0_27_1 nicht vorhanden`. 
`SAPUI5 library/component cc.spreadsheetimporter.v0_27_1 used in application Z_********* not exist`

### Deployment Logs
<details>

```bash
user: csorder $ npm run deploy -- -y
 
> csorder@0.0.1 deploy
> npm run build && fiori deploy --config ui5-deploy.yaml && rimraf archive.zip -y
 
 
> csorder@0.0.1 build
> ui5 build --config=ui5.yaml --all --clean-dest --dest dist
 
info ProjectBuilder Preparing build for project ui5.********
info ProjectBuilder   Target directory: dist
info ProjectBuilder   Including all dependencies
info ProjectBuilder Processing 2 projects
info ProjectBuilder Cleaning target directory...
info Project 1 of 2: ❯ Building module project ui5-cc-spreadsheetimporter...
info Project 2 of 2: ❯ Building application project ui5.********...
info ui5.******** › Running task escapeNonAsciiCharacters...
info ui5.******** › Running task replaceCopyright...
info ui5.******** › Running task replaceVersion...
info ui5.******** › Running task minify...
info ui5.******** › Running task generateFlexChangesBundle...
info ui5.******** › Running task generateComponentPreload...
warn lbt:bundle:Builder Module ui5/*******/utils/locate-reuse-libs.js requires top level scope and can only be embedded as a string (requires 'eval')
info ProjectBuilder Build succeeded in 1.29 s
info ProjectBuilder Executing cleanup tasks...
 
Confirmation is required to deploy the app:
 
    Application Name: Z_*******
    Package: Z_*******ER_UI
    Transport Request: M******
    Destination: mui
    SCP: false
   
    
✔ Start deployment (Y/n)?
 
… yes
info abap-deploy-task Z_******* Creating archive with UI5 build result.
info abap-deploy-task Z_******* Archive created.
info abap-deploy-task Z_******* Starting to deploy.
info abap-deploy-task Z_******* Z_******* found on target system: true
error abap-deploy-task Z_******* Request failed with status code 400
error abap-deploy-task Z_******* SAPUI5-Anwendung Z_******* wurde nicht erfolgreich hochgeladen oder registriert
error abap-deploy-task Z_******* SAPUI5-Anwendung Z_******* wurde nicht erfolgreich hochgeladen oder registriert
info abap-deploy-task Z_******* Please copy/paste this URL in a browser for more details:
info abap-deploy-task Z_******* http://*******:8000/sap/opu/odata/iwbep/message_text;o=LOCAL/
info abap-deploy-task Z_******* ***** Upload von SAPUI5-App oder -Bibliothek aus ZIP-Archiv in SAPUI5-ABAP-Repository *****
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* Standardmodus aktiv: Kurzprotokoll
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* 126 Dateien in Archiv gefunden.
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* * Parameter *
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* Die Textdateien werden mit Hilfe der Standardeinstellungen identifiziert.
info abap-deploy-task Z_******* Die Binärdateien werden mit Hilfe der Standardeinstellungen identifiziert.
info abap-deploy-task Z_******* Nicht zu berücksichtigende Dateien und Ordner werden mit Hilfe der eingebauten Standardeinstellungen identifiziert.
info abap-deploy-task Z_******* Name des SAPUI5-Repository "Z_*******" wurde aus dem entsprechenden Importparameter identifiziert.
info abap-deploy-task Z_******* Transportauftrag "M*******" wurde aus dem entsprechenden Importparameter identifiziert.
info abap-deploy-task Z_******* Name der externen Codepage "UTF8" wurde aus dem entsprechenden Importparameter identifiziert.
info abap-deploy-task Z_******* Akzeptanz Unix-artiger Zeilenendemarker in Textdateien wurde aus dem entsprechenden Importparameter identifiziert.
info abap-deploy-task Z_******* Unix-artige Zeilenende-Marker in Textdateien werden akzeptiert.
info abap-deploy-task Z_******* Deltamodus wurde aktiviert.
info abap-deploy-task Z_******* Wird im sicheren Modus ausgeführt
info abap-deploy-task Z_*******
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* Bestehendes SAPUI5-ABAP-Repository Z_******* wird aktualisiert
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* UPLOAD FILE   : Component-preload.js (Text)
info abap-deploy-task Z_******* UPLOAD FILE   : manifest.json (Text)
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* * Anwendungsindex wird aktualisiert *
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* Anwendungsprotokollnachrichten:
info abap-deploy-task Z_*******
error abap-deploy-task Z_******* In Anwendung Z_******* verwendete SAPUI5-Bibliothek/Kompon. cc.spreadsheetimporter.v0_27_1 nicht vorhanden
info abap-deploy-task Z_******* Please copy/paste this URL in a browser for more details:
info abap-deploy-task Z_******* http://*******:8000/sap/opu/odata/iwbep/message_text;o=LOCAL/
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* Details finden Sie im Anwendungsprotokoll (SLG1) im Mandanten 000 für Objekt /UI5/APPIDX.
info abap-deploy-task Z_*******
error abap-deploy-task Z_******* SAPUI5-Anwendung Z_******* wurde nicht erfolgreich hochgeladen oder registriert
info abap-deploy-task Z_******* Please copy/paste this URL in a browser for more details:
info abap-deploy-task Z_******* http://*******:8000/sap/opu/odata/iwbep/message_text;o=LOCAL/
info abap-deploy-task Z_*******
info abap-deploy-task Z_******* * Erledigt *
error abap-deploy-task Z_******* SAP_Transaction:
error abap-deploy-task Z_******* SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
error abap-deploy-task Z_******* Deployment has failed.
error abap-deploy-task Z_******* Change logging level to debug your issue
error abap-deploy-task Z_*******   (see examples https://github.com/SAP/open-ux-tools/tree/main/packages/deploy-tooling#configuration-with-logging-enabled)
ERR! builder:custom deploy-to-abap Request failed with status code 400
Command deploy failed with error Request failed with status code 400
```

</details>

![image](https://github.com/SAP/open-ux-tools/assets/13335743/faa878e7-35c9-4034-8e61-461388d83a2b)

## System

![image](https://github.com/SAP/open-ux-tools/assets/13335743/d4072d46-e62f-47bd-9feb-89d90126312b)

#### Version/Components/Environment	
BAS  
@sap/ux-ui5-tooling : 1.11.1

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
@marianfoo the deploy tooling here is "just the messenger", the error is coming from the underlying `UI5_REPOSITORY_SERVICE`, maybe @MatthiasSchmalz can help here? Or it is something in the packaging, @petermuessig ?

**Comment by marianfoo** [comment]
I thought that you would show the same error that I show in the logs above. There it is also displayed as an error.  
Why is the deployment executed anyway? I assume that also executes the backend and you send only the data?

**Comment by tobiasqueck** [comment]
> I thought that you would show the same error that I show in the logs above. There it is also displayed as an error. Why is the deployment executed anyway? I assume that also executes the backend and you send only the data?

The tools are just packaging everything and push it to the service. We then either get a happy 200 back or something else. If it is something else, we also receive the log messages from the backend and just push them to the local logger. Everything between sending the request and receiving the response is a black box from the tooling perspective.
Or did I misunderstand your question?

**Comment by marianfoo** [comment]
No, this is correct. That's exactly how I suspected it.
Interesting that then an error comes back and deployment is executed anyway.
In my case this error should be ignored anyway, because I don't want to deploy the component. But this is not the problem of Fiori Tools.

**Comment by marianfoo** [comment]
Then the influence here is small and the issue can be closed.
Is @MatthiasSchmalz  then a contact person or who could I turn to with this?

**Comment by marianfoo** [comment]
Problem not applicable to Fiori Tools

**Comment by MatthiasSchmalz** [comment]
The deploy service also performs some post checks whether the deployment is consistent. They happen after the deployment but can still indicate problems.
In your case it is because a dependency can't be resolved because the 3rd party library is not known.

In your case it looks like you deploy multiple UI5 repositories which all contain a copy of the reuse component in a subfolder, which is not declared as embedded in the root manifest.json.
The best way would be to deploy the reuse component once in an own repository. Then it would be known to the system and unique. Then the error would disappear.

**Comment by marianfoo** [comment]
Hi @MatthiasSchmalz 
Thank you for your comment.
I deploy a UI5 app with a component in the UI5 app.
I could avoid the error if I specify "embeds".
https://docs.spreadsheet-importer.com/pages/GettingStarted/#error-librarycomponent-used-in-application-does-not-exist
Unfortunately only on on-premise S/4HANA systems.
Unfortunately, this does not work with the BTP ABAP systems (ABAP Environment/ S/4HANA Public Cloud) plus there is also another error on this systems when the system performs checks..
I am currently in the process of creating an example and opening a support case.

Deploying the component directly is an option, but not always the best one in my use case.
I would like to offer both options

**Comment by marianfoo** [comment]
Hi @MatthiasSchmalz 
i created a ticket `217791/2024`.
I can not deploy a app to ABAP Cloud with a component inside of the app.
It works on On-Premise System.
