### ISSUE TITLE
[Feature] Disable Control Property Editor for ADP projects with UI5 version lower than 1.71

### ISSUE THREAD

**Issue by GDamyanov** [SAP/open-ux-tools#1405]
As a **developer**,
I want to **disable the CPE for ADP projects with ui5 version lower than 1.71**,
so that I **cannot open CPE**

### Description

Control Property Editor should be disabled for ADP projects with UI5 version (set in the ui5.yaml in ui5-proxy-middleware) lower than 1.71 
### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a ADP project with UI5 version lower than 1.71 set in ui5.yaml in the ui5-proxy-middleware
**when** I start the Control Property Editor
**then** I should see error message with text "The current SAPUI5 version set for this Adaptation project is {some version}. The minimum version to use for SAPUI5 Adaptation Project and its SAPUI5 Visual Editor is 1.71" and a new browser tab with Control Property Editor should not be loaded.

### Tasks

- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by tobiasqueck** [comment]
@GDamyanov what should happen in such case? Should an error be shown or ... ? Should the preview without CPE work?

**Comment by GDamyanov** [comment]
> @GDamyanov what should happen in such case? Should an error be shown or ... ? Should the preview without CPE work?

Error message should be shown in the console and the CPE should not be loaded.

**Comment by tobiasqueck** [comment]
> Error message should be shown in the console and the CPE should not be loaded.

Your implementation in #1423 is preventing also the preview (no editor). Is this also the goal or should the plain preview work?

**Comment by GDamyanov** [comment]
> > Error message should be shown in the console and the CPE should not be loaded.
> 
> Your implementation in #1423 is preventing also the preview (no editor). Is this also the goal or should the plain preview work?

The preview should also be  stopped.
