### ISSUE TITLE
BUG - Implementation of primary and secondary buttons

### ISSUE THREAD

**Issue by korotkovao** [SAP/open-ux-tools#1413]
### Description
Verify we have the correct implementation of primary and secondary buttons.
This is needed for the correct styling when using different **VS Code themes**.

### Steps to Reproduce
1. Open SAP Systems view in VS COde. SAP Fiori (pencil and wrench on the left), Add SAP System (plus icon)
2. Go to Settings
3. Change to Light Modern theme
4. Observe Save button looking wrong and hard to read.

### Expected results

Text color change applies separately to primary and secondary buttons
color: var(--vscode-button-foreground, #FFFFFF);
color: var(--vscode-button-secondaryForeground, #FFFFFF);

![image](https://github.com/SAP/open-ux-tools/assets/98463389/c0e195b4-dbd8-4eaa-90b1-4ab1d57ccc0b)

### Actual results

Text color change applies to both buttons.

### Screenshots
![image](https://github.com/SAP/open-ux-tools/assets/98463389/c74a81dd-d1e5-42c2-828f-de3ad279a62d)

![image](https://github.com/SAP/open-ux-tools/assets/98463389/77e80975-d91c-45c2-b7d3-987975a361c1)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by gpeuc** [comment]
Essentially, it would appear that Primary and Secondary button weren't implemented correctly as indeed two separate buttons, but instead some trickery was used to just override the background colour of one of the buttons to make the other button. We should properly implement 2 buttons coming from the UI components.
