### ISSUE TITLE
TBI - Add options to the writers (considerations for CAP)

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#1516]
### Description (include screenshots)

There is a need for more options to be available to determine what files and configs are added to the Fiori apps.
In some cases there is a need to prevent certain files being added, or additional data is needed. See comments for details.

### Value
Reduces the need to patch or modify the app and it's files post generation.

### Architecture Elaboration

Yes

### Tasks
- [ ] Task 1

**Comment by cianmSAP** [comment]
### Issue 1 - metadata.xml
**Description** : The writing of `/localService/metadata.xml` is not needed for CAP applications and can be skipped in the writing phase.

**Proposal** : Add a property to prevent this file being written. 

**Question** : Is the [call to the odata service writer](https://github.com/SAP/open-ux-tools/blob/11bb8fa9148a4162bc7ac32e2fc24b7530fcea32/packages/fiori-elements-writer/src/index.ts#L70) required at all? Or we should just prevent the file being written [here](https://github.com/SAP/open-ux-tools/blob/11bb8fa9148a4162bc7ac32e2fc24b7530fcea32/packages/odata-service-writer/src/index.ts#L120) 

### Issue 2 - typeRoots
**Description** : Currently the paths for the type roots [are hardcoded](https://github.com/SAP/open-ux-tools/blob/11bb8fa9148a4162bc7ac32e2fc24b7530fcea32/packages/ui5-application-writer/templates/optional/typescript/tsconfig.json#L19). In the case where the `node_modules` folder containing the required types is in a parent folder, the types are not found resulting in errors in .ts files.

**Proposal** : Add an additional property e.g `projectRoot` to the [App interface
](https://github.com/SAP/open-ux-tools/blob/11bb8fa9148a4162bc7ac32e2fc24b7530fcea32/packages/ui5-application-writer/src/types.ts#L13)

### Issue 3 - proxy middleware + opa tests

**Description** :  If the proxy middleware is not deisred, rather than removing it post generation, provide an option to prevent this being written to the yaml files. The ui5-test-writer would then require additional params, i.e the framework url e.g `https://ui5.sap.com` and the ui5 version. These would be added diretly to the `opaTests.qunit.html`

**Proposal** : Add an additional property e.g `addProxyMiddleware` to the [App options
](https://github.com/SAP/open-ux-tools/blob/11bb8fa9148a4162bc7ac32e2fc24b7530fcea32/packages/ui5-application-writer/src/types.ts#L57) , which would default to true. In the case that it is false, do not add the proxy middleware config and pass the framework url and ui5version to the ui5-test-writer.

**Question** : The `testsuite.qunit.html` uses the [qunit-redirect.js](https://ui5.sap.com/sap/ui/qunit/qunit-redirect.js) which I've been unable to get working without a proxy. So I'm wondering can this work without a proxy, or it should be not written at all in that case.


@devinea @tobiasqueck any feedback is appreciated

**Comment by tobiasqueck** [comment]
I am also not to sure about `Issue 3`. For the normal preview, we decided not to use a local preview script but added a script to the root project starting the CAP server including our project. Shouldn't we follow the same approach for the OPA tests? I'd assume these are also started with the CAP server, just with a different url to be opened.

**Comment by cianmSAP** [comment]
> I am also not to sure about `Issue 3`. For the normal preview, we decided not to use a local preview script but added a script to the root project starting the CAP server including our project. Shouldn't we follow the same approach for the OPA tests? I'd assume these are also started with the CAP server, just with a different url to be opened.

I'm not sure how adding a script to open the file would solve the issue?

The `.html` files [testsuite.qunit.html](https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-test-writer/templates/common/testsuite.qunit.html) and [opaTests.qunit.html](https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-test-writer/templates/v4/integration/opaTests.qunit.html) in the `ui5-test-writer` use scripts with relative paths .. which (corret me if I'm wrong) is assuming that their is a proxy that will correctly leverage the test scripts @ ui5.sap.com or sapui5.hana.ondemand.com

The ui5.yamls for cap is minimal, with no proxy config (I'm trying to prevent it being written rather than remove it post generation in https://github.com/SAP/open-ux-tools/pull/1533). 

So the issue being, we are generating these files which point to external files which can't be found without the proxy

**Comment by cianmSAP** [comment]
Closing as issue 1 has been resolved, and the other two issues are being discussed seperately
