### ISSUE TITLE
BUG -  Types are not exported from `@sap-ux/jest-file-matchers`

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#1664]
### Description

Types can only be imported as deeply nested `dist` references as the module is not exporting the types.

```
export * from './matchers';
```

Should be:

```
export * from './matchers';
export * from './matchers/types';
```

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by cianmSAP** [comment]
Closing as types are now exported
