### ISSUE TITLE
BUG - generated FLP sandbox does not show application title and description

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#1666]
### Description
When previewing an application in generated Fiori Launchpad sandbox (`flp.html`), the application title and description is not displayed correctly. Instead, `{` and `}` is shown.

### Steps to Reproduce
1. Download and extract [fe_lrop_v4_odata_none-2024-02-190928.zip](https://github.com/SAP/open-ux-tools/files/14329178/fe_lrop_v4_odata_none-2024-02-190928.zip)
2. Start a terminal in extracted folder `fe_lrop_v4_odata_none-2024-02-190928`
3. Execute `npm install`
4. Execute `npm start`
5. A browser starts, change `flpSandbox` to `flp` in the URL, the URL should look like 

### Expected results
FLP sandbox is shown with the application title and description

### Actual results
Instead of title and description `{` and `}` is shown.

### Screenshots
<img width="628" alt="image" src="https://github.com/SAP/open-ux-tools/assets/66327622/f0f3c7b4-8da9-493b-8d04-02a598dcb6ad">

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [x] Windows
- [ ] Other

### Problem
Most likely the issue is due the way application and title are generated in the flp sandbox: 
<img width="768" alt="image" src="https://github.com/SAP/open-ux-tools/assets/66327622/df6e4a13-1f38-4992-949b-f0045358f2c4">

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by heimwege** [comment]
solved with #1755
