### ISSUE TITLE
TBI - Add more CAP specific items to `@sap-ux/project-access`

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#1736]
### Description (include screenshots)
Add function `isCapProject` and other CAP specific const values

### Value
Enhances capabilities of @sap-ux/project-access in regards to CAP

### Architecture Elaboration
No

### Tasks
- [ ] Task 1

**Comment by devinea** [comment]
@cianmSAP Would `getProjectType` or `getCapProjectType` not cover this?

**Comment by devinea** [comment]
> @cianmSAP Would `getProjectType` or `getCapProjectType` not cover this?

I see the PR now, that it is a convenience method. 👍

**Comment by cianmSAP** [comment]
Closing as method has been added
