### ISSUE TITLE
TBI - `@sap-ux/project-access` - add missing constants 

### ISSUE THREAD

**Issue by mikicvi-SAP** [SAP/open-ux-tools#1799]
### Description (include screenshots)
Will add missing constants under `DirName` such as
```
    Schemas = '.schemas',
    Pages = 'pages',
    Webapp = 'webapp',
```
Internal issue 28284.

### Value
Allow the use of constants in development, instead of hardcoding the strings.

### Architecture Elaboration
Does it requires architecture elaboration?
- Yes

### Notes
- Discovered as a part of consuming `@sap-ux/project-access` into Fiori Tools

### Tasks
- Create constants

**Comment by longieirl** [comment]
A suggestion is to look into each module consuming `project-access` and ensure if there are duplicate constants that these are refactered out to `project-access` instead;
```
export enum DirName {
    Sapux = 'src',
    Schemas = '.schemas',
    Pages = 'pages',
    Webapp = 'webapp',
    Temp = '.tmp',
    Changes = 'changes',
    LocalService = 'localService',
    Controller = 'controller',
    View = 'view',
    Fragment = 'fragment',
    Ext = 'ext',
    VSCode = '.vscode',
    AppConfig = 'appconfig',
    Db = 'db',
    Csv = 'csv',
    Data = 'data',
    Mockdata = 'mockdata',
    Dist = 'dist'
}
```

**Comment by longieirl** [comment]
Consumed into tool-suite, issue can now be closed.
