### ISSUE TITLE
TBI - Continuously watch and improve code quality

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#180]
### Description (include screenshots)
Could using https://sonarcloud.io/ help us improve code quality?

### Value
Being able to continuously watch code quality helps keeping the code base maintainable.

### Architecture Elaboration
Not really, but a technical investigation.

### Tasks
- [x] Investigate
- [x] Try
- [x] Finalize :)

**Comment by devinea** [comment]
Thanks @kranthie-sap Sonar seems working well now. 
https://sonarcloud.io/summary/overall?id=SAP_open-ux-tools

@tobiasqueck - OK to close?

**Comment by tobiasqueck** [comment]
Looks great, thank you!
