### ISSUE TITLE
BUG - preview middleware served launchpad not able to navigate to (fiori elements) application in UI5 122.x

### ISSUE THREAD

**Issue by heimwege** [SAP/open-ux-tools#1841]
Hey hey 👋🏻 

In UI5 >=1.122.x the launchpad served by the preview middleware is no longer able to open a Fiori Elements app.

Details see internal incident `DINC0116030`

Seems like `NavTargetResolution` is now required 🤷🏻 

### Expected results

App opens on click of tile

### Actual results

Error message:

```
App could not be opened because the SAP UI5 component of the application could not be loaded.
Failed to load UI5 component for navigation intent "#Samples-display"
```

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by zdravko-georgiev** [comment]
@heimwege I am still able to successfully run a Fiori elements application locally **without** having the `NavTargetResolution`. Are you able to reproduce the issue locally?

**Comment by heimwege** [comment]
@zdravko-georgiev my CAP Java FE playground repo worked in 1.120.11 and didn't work once I upgraded to 1.122.2. So basically as described in the internal incident. The solution as also taken from there.

**Comment by zdravko-georgiev** [comment]
@heimwege I can reproduce it with your CAP Java FE playground repo. This is a very interesting issue, because if I switch the loading of UI5, hence use the `ui5-proxy-middleware` and load UI5 from `ui5.sap.com` and NOT from npmjs, then the issue does not occur.

**Comment by heimwege** [comment]
I tried the same and yes, the navigation as such works when using the proxy which is strange enough, but the application seems to be broken too. I get the following FE error that I don't get with the implemented fix and the sources are served directly without the proxy:

<img width="656" alt="image" src="https://github.com/SAP/open-ux-tools/assets/73878785/fb35c67b-bf3b-4678-8f18-0ed333dd8b5a">

This is indeed really strange as it seems the served UI5 sources are not identical 🤔

**Comment by zdravko-georgiev** [comment]
> I tried the same and yes, the navigation as such works when using the proxy which is strange enough, but the application seems to be broken too. I get the following FE error that I don't get with the implemented fix and the sources are served directly without the proxy:
> 
> <img alt="image" width="656" src="https://private-user-images.githubusercontent.com/73878785/323522197-fb35c67b-bf3b-4678-8f18-0ed333dd8b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Mjg3MjIsIm5iZiI6MTcxMzQyODQyMiwicGF0aCI6Ii83Mzg3ODc4NS8zMjM1MjIxOTctZmIzNWM2N2ItYmYzYi00Njc4LThmMTgtMGVkMzMzZGQ4YjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA4MjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODFhMmQ1NWI0NWRkNWVmNzY5MWQ4NmIzNTA1MWQ4MTFiZjA1NGNmMjQ2NzY2OGIyNTIwZmEwOGY5MDlhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PoUwlUxKqHyMU348LeL37DVJnn0oz9XQqkH2DChZkD8">
> This is indeed really strange as it seems the served UI5 sources are not identical 🤔

Please try `Empty Cache and Hard Reload` in the browser tab. Sometimes there are cache issue when switching between npmjs and ui5.sap.com versions

**Comment by zdravko-georgiev** [comment]
> That solved it, thanks. I thought I'm on the safe side if I just use `sap-ui-xx-viewCache=false`. Seems not to be the case 🙈

This one only disables the cache for the XML Views 😉

**Comment by tobiasqueck** [comment]
@heimwege, the issue can be closed correct? If not, and I misunderstood, please reopen.

**Comment by heimwege** [comment]
@tobiasqueck fine for me, but as there will be no downport closing this issue means preview middleware is broken for >= 1.122.x < 1.124.x. So at least the readme should be adjusted accordingly.
@zdravko-georgiev please correct me if I'm wrong.

**Comment by tobiasqueck** [comment]
Maybe I misread the discussion, however, I thought to understand that it is an issue in UI5 independent of the middleware i.e. if you create a local flp.html file and do the same, you run into the same issue.

**Comment by heimwege** [comment]
Depends on how your local flp configuration looks like 😄
Assuming you use the very same config for the flp sandbox the preview middleware uses in its flp template, my understanding is that you will run into exactly the same issue (in case you use the ui5 sources from npmjs! Using the proxy to load the ui5 sources works 🙈). So even if this issue is not a preview middleware issue, there's a broken flp sandbox config in 1.122.x and 1.123.x that leads to a broken flp in the preview middleware. So either the UI5 colleagues do a downport of the fix (which they declined) or we should at least add this information to the readme of the preview middleware. That's why I re-opened the issue that adjusting the readme is not forgotten.

**Comment by tobiasqueck** [comment]
Ok, now I am getting it. We usually recommend to use the `ui5-proxy-middleware` (standalone or included in the `@sap/ux-ui5-tooling), and as far as I understand, then you won't have the issue. So, we are talking about a corner case here.

I am a little reluctant to add this to the README because it could create the impression that all known issue with the other packages are listed, which we don't. Since these are no long term release versions of UI5, I'd still prefer not doing anything here.

What do you think?
