### ISSUE TITLE
TBI - (deploy-tooling): move `replaceEnvVariables` out of deploy-tooling so it can be exported

### ISSUE THREAD

**Issue by mikicvi-SAP** [SAP/open-ux-tools#1880]
### Description (include screenshots)
- Refactor the [`replaceEnvVariables`](https://github.com/SAP/open-ux-tools/blob/main/packages/deploy-tooling/src/base/config.ts#L25-L40) out of deploy-tooling to ui5-config module so it can be exported.
- deploy-tooling is not a library so the method should not be exposed here.

### Value
- Developers will be able to use this function outside of the module.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [x] Move the `replaceEnvVariables` to ui5-config
- [x] Move relevant tests

**Comment by longieirl** [comment]
Currently consumed in Fiori tools and working as expected.
