### ISSUE TITLE
TBI - Add `authenticationType` to `FioriToolsProxyConfigBackend`  with comments

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#1965]
### Description (include screenshots)
 Add `authenticationType` to `FioriToolsProxyConfigBackend` and ability to add inline comments to yaml configs

### Value
This will users to generate yaml configs with authenticationType added to the backend config. In the case of `reentranceTicket` auth type, a default comment will be added.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by tobiasqueck** [comment]
@cianmSAP adding inline comments is already support e.g. we are using it at https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-config/src/middlewares.ts#L49. Or do you need something else?

**Comment by cianmSAP** [comment]
> @cianmSAP adding inline comments is already support e.g. we are using it at https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-config/src/middlewares.ts#L49. Or do you need something else?

Hi @tobiasqueck , yes I'm utilising this when [addFioriToolsProxydMiddleware](https://github.com/SAP/open-ux-tools/blob/d9212217cdefb541754bb6eb7a0f9e8445c02216/packages/ui5-config/src/ui5config.ts#L224) is called. But I needed an additional method to add the comments when [addBackendToFioriToolsProxydMiddleware](https://github.com/SAP/open-ux-tools/blob/d9212217cdefb541754bb6eb7a0f9e8445c02216/packages/ui5-config/src/ui5config.ts#L241) is used

As there can be multiple backends added to the yaml there was some additional work needed.

 I've opened up a [PR](https://github.com/SAP/open-ux-tools/pull/1967), if you can take a look.

**Comment by cianmSAP** [comment]
Closing as updates have been made to implement this
