### ISSUE TITLE
FEATURE - Add deployment writer module to support adding ABAP deployment configuration

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#2006]
As a developer using SAP Fiori tools, I want to add ABAP deployment configurations to my app, so that I am able to deploy my app to an ABAP target system.

### Technical Design
New module : 
- @sap-ux/deployment-writer

### Acceptance Criteria

**Given** I have a Fiori project with no ABAP deployment configuration
**when** I invoke this writer with the correct data
**then** the ABAP deployment configuration will be added to my Fiori project

### Tasks
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by cianmSAP** [comment]
Closing as writer is published
