### ISSUE TITLE
BUG - Eslint does not cover post-deployment applications.

### ISSUE THREAD

**Issue by ciaradaly2021** [SAP/open-ux-tools#213]
### Description
Eslint throws many errors after deployment of apps due to dist folder being created post-deployment. Only happens for fiori-freestyle as elements has already been patched.

### Steps to Reproduce
1. Create freestyle application with eslint configurations
2. Deploy app
3. run eslint

### Expected results

No error, even after deployment.

### Screenshots
![ff_issue](https://user-images.githubusercontent.com/95859201/145396632-c6cfdf13-7a20-41d5-9890-ec248541c871.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
@devinea has this been fixed with your PR #227

**Comment by devinea** [comment]
Yes. Thanks for the reminder.
