### ISSUE TITLE
BUG - Deployer exits with code 1 when declaring custom control libraries deployed as BSP apps in manifest.json

### ISSUE THREAD

**Issue by marcelschork** [SAP/open-ux-tools#2185]
### Description
When uploading UI5 apps to SAP On-Prem (SAP_BASIS 7.50 SP 28 / SAP_UI 7.54 SP 14) the deployer always exits with code 1 what suggests that the deployment was not successful. But in our case this isn't true, because technically the deployment is successful - all files are uploaded and the app index is calculated as well. 

If we remove the library declaration from the manifest.json the deployment is successful. 

### Steps to Reproduce
1. Deploy a custom contol library to SAP On-Prem as BSP application
2. Include the library in any UI5 application by declaring the lib dependency in manifest.json
3. Build & deploy the app tp SAP On-Prem using fiori deployer 
```sh
fiori deploy --archive-path archive.zip --yes --strict-ssl false
```

### Expected results
The custom library should be recognized correctly or at least the exit code should be 0 to indicate a correct deployment. 

### Actual results
The deployment exits with code 1 that indicates a failed deploymend, although technically everything is OK. 

#### Pipeline log
<img width="952" alt="pipeline_log" src="https://github.com/user-attachments/assets/58e16d17-0934-4ece-98b8-75f91698cf3c">

#### manifest.json
![image](https://github.com/user-attachments/assets/de5287de-b146-48fb-9473-d7edfe585a32)

#### Bootstrap
![image](https://github.com/user-attachments/assets/774010e6-e5f6-43b5-911b-8fe8cecbc3f4)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [x] Ubuntu
- [ ] Windows not tested

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by longieirl** [comment]
@marcelschork According to the bootstrap screenshot, the lib is in `ZCAX_LIBUI5V171/lidl.lib.ui5` which indicates that the `manifest.json` of the lib is not in the root of `ZCAX_LIBUI5V171` but in a sub folder which causes problems.

Can you confirm if the `manifest.json` is in `lidl.lib.ui5` folder?  if so, please correct your deployment to only deploy the content of the `lidl.lib.ui5` folder.  Then app index will know about the `lidl.lib.ui5` library and won’t complain when the app using it is deployed.

**Comment by marcelschork** [comment]
Hi, thanks @longieirl. This solved our problem. The issue can be closed!
