### ISSUE TITLE
TBI - Update generator to fallback to Application modeler keytar installation

### ISSUE THREAD

**Issue by korotkovao** [SAP/open-ux-tools#2224]
### Description (include screenshots)
There are sometimes issues where keytar was not installed when the Fiori generator was installed on windows. It was missing from the `generator\node_modules` folder.

This may be due to virus scanner or hardening of the windows environment (the customer issue above was for a government installation and had very restricted user rights). However, the keytar always seems to be successfully installed as part of the saved systems panel with the application modeler.

The secure store open source module currently attempts to load keytar, but if it fails, then it falls back to load it from VSCode. See https://github.com/SAP/open-ux-tools/blob/5b572582885880c213c857f9430165f12f92bec8/packages/store/src/secure-store/index.ts#L8-L36

However, VSCode removed keytar a number of months ago.

The suggestion in this TBI is to fallback to loading keytar from the Application Modeler extension node_modules folder  if it cannot be loaded.

## Value
Help with support issues around keytar, of which there are many, whilst acknowledging that keytar is to be replaced in the short term.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by devinea** [comment]
Done in https://github.com/SAP/open-ux-tools/pull/2230 and subsequently replaced by zowe
