### ISSUE TITLE
BUG - Selected control is not visible in outline 

### ISSUE THREAD

**Issue by nahmed22** [SAP/open-ux-tools#2245]
### Description
The selected control occasionally becomes hidden when it's selected, particularly if the control has already been scrolled up or down in the outline. It gets scrolled to the top and ends up underneath the `Search Outline` control.

### Steps to Reproduce
1. Start CPE from an Adaptation Project 
2. scoll down to end of the control.
3. Select any control from the preview.
4. The selected control is scrolled to the top, remaining underneath the `Search Outline` control, and is not visible.

### Expected results
![image](https://github.com/user-attachments/assets/209ba8f9-e78c-467b-8864-3918c207bb9e)

### Actual results
![image](https://github.com/user-attachments/assets/7ef9f846-5589-43eb-bb33-3a305607d1e4)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by voicis** [comment]
The issue appeared after #2197
