### ISSUE TITLE
Provide some documentation on how to debug

### ISSUE THREAD

**Issue by lboehm** [SAP/open-ux-tools#231]
### **Issue Description**

I would like to contribute to this repo and I don't know how to debug the code. I've read the [Contributing section](https://github.com/SAP/open-ux-tools#contributing) but I can't find an answer there.

I had the same issue with easy-ui5 and [Marius provided some info](https://github.com/ui5-community/generator-ui5-project/issues/25), so I could create pull requests. It would be great if this repo had some similar documentation.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [X] Documentation is missing
- [ ] Other

Thank you and best regards
Lukas

**Comment by theStiggySpd** [comment]
Hi Lukas,
Thanks for your interest. We will get back to you 
Thanks, 
Sushant
