### ISSUE TITLE
BUG - Manifest changes are not reflected after reload

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#2520]
### Description
While using Adaptation Editor if you make a change that modifies manifest, then it will not be reflected in the preview. You can only see it after restarting the editor (from the terminal).

This issue was introduced by #2429

### Steps to Reproduce
1. Checkout branch from #2510
2. Start Adaptation Editor for a LROP V2 application
3. Click on `Enable/Disable "Semantic Date Range" for Filter Bar`
4. Save and reload

### Expected results
The semantic date range configuration is change is reflected in the preview (quick action should also show the opposite name).

### Actual results
It still shows the original value.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by MN-public** [comment]
@mmilko01 Would it be ok if I assign this issue to you?

**Comment by mmilko01** [comment]
@MN-public I took it. I will discuss with Davis and our team for possible solutions here.

**Comment by mmilko01** [comment]
@MN-public We need do a manual test of the PR from our side and we will merge the PR once done. If everything with the testing passes ok, we should be able to merge before the release.

**Comment by mmilko01** [comment]
@MN-public @voicis  The fix is now merged. There is another issue noticed during the testing, which doesn't seem to be related to this fix. I already discussed with @voicis for further steps.
