### ISSUE TITLE
BUG - Exception while using FPM writer 

### ISSUE THREAD

**Issue by stefanschreck** [SAP/open-ux-tools#327]
### Related Feature
FPM writer (for custom columns)

### Description
When the FPM writer is embedded in another module as part of its delivery, the generation ends up in an exception. 
This is due to the usage of relative paths in connection with `_dirname`, as for example at https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/column/index.ts:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/22190895/153414759-e8a8da98-f842-46aa-a810-7bef56ac3cb4.png">
 
As a workaround I tried to copy the templates to the right location as part of my consumer module (@sap/ux-specification), but this copy finally got removed during the production. The workaround is not a solution, and we have to replace the relative paths at the FPM writer, e.g. by using `require(.resolve)`. 

### Steps to Reproduce
Exception when running the latest ux-engineerin/toolsuite against the  @sap/ux-specification.
Try to add a new custom column from the outline of Page editor
==> Exception:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/22190895/153415624-4da1fec9-a28f-4313-b811-1c86323c99ac.png">

### Expected results
Template can be identified, and is used to create the new column.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by stefanschreck** [comment]
Hello @tobiasqueck 
I had opened the ticket so that we can discuss the approach once again, maybe in a bigger round. 
Especially Donal saw some problems by using __dirname. Austin already gave me the hint with CopyPlugin, that's what I already productively use in specification.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/22190895/156323329-7ebe3447-32fb-46d2-b053-b4ae903bd470.png">
With this approach I managed to get  the consumption up and running at VSC, but I am still facing issues in BAS.
And the CopyPlugIn is jus a kind of workaround for the problem, isn't it?

**Comment by donal-tobin-sap** [comment]
In general I feel it is fragile to presume details about how the installation is laying out the modules on disk to access files in one module from another.

**Comment by donal-tobin-sap** [comment]
Unfortunately the import equivalent to require.resolve to get the path of the module is only experimental and thus not usable.

https://nodejs.org/api/esm.html#introduction
I am only reading the documentation for this in depth now for the first time, so I may have missed something, 
But as I see it the `import.meta.url` should allow the actual folder of the module to be seen, the template module could then expose this value in a function call to make the real template folder path available to the consuming modules.
That is the template module has a function / class something like Templates.getTemplatesFolder()

**Comment by tobiasqueck** [comment]
Looking at the different options, I think `require.resolve`, `import.meta.url` and `__dirname` all have the same issue. It gives you a location of the executable code and we need to use it to refer to a folder containing our templates. If transpiled code and template folder are moved separately then we have an issue.
Adding a small js file into the template folder exposing `getTemplatesFolder` (returning  `__dirname`) would solve but `feels` not right.

**Comment by stefanschreck** [comment]
Listing the FPM writer under `externals` worked fine now. The use of `CopyPlugin`was superfluous and will get eliminated.
@donal-tobin-sap Do you agree or disagree to the arguments from @tobiasqueck? Question is if we can improve the coding, or not.

**Comment by tobiasqueck** [comment]
Maybe using `path.join(require.resolve('sap-ux/fe-fpm-writer'), '../templates')` would slightly improve it because it now fits with the usual code in `dist` (or `src` or `lib`) and templates in a folder on the same level.

**Comment by donal-tobin-sap** [comment]
> Maybe using `path.join(require.resolve('sap-ux/fe-fpm-writer'), '../templates')` would slightly improve it because it now fits with the usual code in `dist` (or `src` or `lib`) and templates in a folder on the same level.

If you can use require then this is what I would recommend as well.

However if you cannot use require then I believe we should discuss it further, as I believe that having a small javascipt in the module is nicer as it hides the details of where the files are kept within the npm module.

**Comment by tobiasqueck** [comment]
I would suggest to close this one. If someone else runs into the issue they will hopefully find this discussion and if then there is a need to revisit the topic, we do it.

**Comment by stefanschreck** [comment]
OK for me, as I have a solution for my urgent problem
