### ISSUE TITLE
FEATURE - Worklist OData V4 support

### ISSUE THREAD

**Issue by quiggs1001** [SAP/open-ux-tools#399]
**As a Fiori developer, I'd like to be able to use an OData V4 data source to generate a Worklist Fiori elements application.**

### Description

The worklist floorplan in the generator supports only V2 data sources currently. In order to generate a Worklist V4 application, it will be an LROP V4 application, but with the setting hideFilterBar=true in the manifest.

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
- Given I choose the Fiori elements Worklist template, I should be able to provide an OData V4 data source and successfully generate the FE Worklist application.

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by IainSAP** [comment]
Closing as merged and tests added.
