### ISSUE TITLE
BUG - the types in the fiori-elements-writer are misleading

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#407]
### Related Feature
Feature request: #72

### Description
I have tried to create a simple Yeoman generator utilizing the`@sap-ux/fiori-elements-writer` module. While using it some of the types did not completely make sense to me. My example is WIP at https://github.com/SAP/open-ux-tools/blob/example-for-writer/examples/simple-generator/src/app/index.ts

#### EntityConfig
Could you please document the interface `EntityConfig` at https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-elements-writer/src/types.ts#L27? It is not clear what `mainEntity.type` does or `navigationEntity.Role`. For `navigationEntity` I also don't understand what `Name` and `EntitySet` exactly do.

#### Template Settings
I wanted to create an instance of the `LROPSettings` and I noticed the option property `template.settings.entityConfig.filterEntityType` which does not have an effect in an LROP template. This is an OVP specific property. Looking closer, I noticed the vice versa `OVPSettings` offer a `mainEntity` that does not belong to OVP. Could you please revisit https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-elements-writer/src/types.ts#L53-L67 and define types so that they match the real options.

### flpAppId
It is defined as property at https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-elements-writer/src/types.ts#L89 and based on my understanding it is only used for local flp sandbox script. Is there any value for the consumer of the `fiori-elements-writer` to configure this one? I would suggest to remove the property from the public api and set it within the writer to simplify the interface.

### Steps to Reproduce
n/a

### Expected results
I have no questions and know exactly what to do :)

### Actual results
I am confused :(

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by devinea** [comment]
@tobiasqueck regarding `flpAppId` we made this variable in tool-suite to allow setting in the template during migration the semantic object and action from the original app. Hard coding did not work in that case. 
It can make sense if during generation the deploy step is executed to also write the semantic object and action into the npm scripts and flp*sandbox.html based on what the user provided. 
So I think we should keep it.

**Comment by tobiasqueck** [comment]
Re-opening to clarify the `flpId` property, the rest is fixed with #411

**Comment by IainSAP** [comment]
Partially addressed with #411

**Comment by tobiasqueck** [comment]
I am closing this one because the open issue with the `flpId` property is handled separately in #441
