### ISSUE TITLE
BUG - utils/locate-reuse-libs.js added without requesting it

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#408]
### Related Feature
Feature request: #72

### Description
I have created my own generator using the `@sap-ux/fiori-elements-writer` module. When calling the generate method I set the `appOptions` property to `undefined` (and also tried `{}`) but in both case the `webapp/utils/locate-reuse-libs.js` script was generated. The only way to not generate it was explicitly setting the `loadReuseLibs: false`.
My example generator is at https://github.com/SAP/open-ux-tools/blob/example-for-writer/examples/simple-generator/src/app/index.ts.

### Steps to Reproduce
Call the `generate`  function from `@sap-ux/fiori-elements-writer`  with all mandatory values BUT none of the optional values.

### Expected results
The file `webapp/utils/locate-reuse-libs.js` is **not** generated.

### Actual results
The file `webapp/utils/locate-reuse-libs.js` is generated.

### Screenshots
n/a

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by IainSAP** [comment]
Fixed #411
