### ISSUE TITLE
BUG - odata-service-writer may fail when bundled

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#580]
### Description
The `OdataService` interface property (https://github.com/SAP/open-ux-tools/blob/main/packages/odata-service-writer/src/types.ts#L15) `client` is interpreted as an `ejs.render` option.  This may lead to failing template rendering when bundling or other side-effects.

`client` is copied as an `ejs` option here: 
https://github.com/mde/ejs/blob/main/lib/ejs.js#L422
https://github.com/mde/ejs/blob/main/lib/ejs.js#L61

We should replace the data property name `client` in calls to `ejs.render`, along with the associated template file variables. Propose that this is renamed to `sapClient`. Note, this does not impact the interface definition for `OdataService` only the property name passed to `render` (which currently are the same).

https://github.com/SAP/open-ux-tools/blob/main/packages/odata-service-writer/src/index.ts#L77 and anywhere else `client` property is passed.

### Steps to Reproduce
Contact @IainSAP for details

### Expected results

Additional client functions should not be added when calling render. 

### Actual results

`client` is interpretted as an `ejs` option.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [x] Windows
- [ ] Other

**Comment by tobiasqueck** [comment]
@IainSAP that is an interesting one! What is the suggested solution? Just rename it to e.g. `sapclient`?
