### ISSUE TITLE
FEATURE - Add Environment check module 

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/open-ux-tools#619]
_As a **Fiori developer** with my project in SAP Business Application Studio,
I want a way to run a check for issues related to destination configuration,
so that I can fix the issue myself based on check results to avoid opening incident with SAP OR provide the results to SAP to minimize the time of initial product support investigations_

### Description
- Environment check is a `check` which can be performed by the end users and thus self-troubleshooting some of the most common occurring issues, currently identified with BTP destination misconfigurations. 
- Environment check can be enhanced by the community and more checks can can be added to make it easer for Fiori developers to troubleshoot.

### Technical Design
@Klaus-Keller and Cian to add.
Also, please use https://www.npmjs.com/package/@sap/bas-sdk for BTP destination specific queries

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I run Environment Check in SAP Business Application Studio 
**when** its triggered by an extension 
**then** I can choose a destination from the list of destinations to run the checks on.

**Given** I run Environment Check in SAP Business Application Studio 
**when** its called by the command line via command `envcheck`
**then** I can pass the destination(s)  to run the checks on.

**Given** I have destination related issues with my Fiori project running in SAP Business Application Studio
**when** when I run Environment Check
**then** an output file containing the check details in markdown file should be created, making it easier to see results or share with product support.

**Given** I have destination related issues with my Fiori project running in SAP Business Application Studio
**when** when I run Environment Check
**then** an output json file containing the detailed request/response of all the calls (e.g. V2/V4 catalog service request) should be created.

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by tobiasqueck** [comment]
@theStiggySpd that one needs a bit more information. Do you expect this to be a module with a CLI that I call from the command line, or is this a collection of functions that you want to integrate somewhere else? Please make sure that this is clear in the acceptance criteria.
In addition, looking at the PR, I am not sure the name is a good fit but I am sure that is easier to discuss wants the acceptance criteria is well defined.
From a technical perspective, please make sure to use the `axios-extension` module since it already provides the abstraction of using destinations and calling their catalog services.

**Comment by Klaus-Keller** [comment]
@tobiasqueck, 
> Do you expect this to be a module with a CLI that I call from the command line, or is this a collection of functions that you want to integrate somewhere else?

Both, the module has a CLI ([packages/environment-check/src/cli/index.ts](https://github.com/SAP/open-ux-tools/pull/628/files#diff-aacc7ccf720328c0fc8469c6a256d217767054b41b040766cabea867e73a777b)) and can be used programmatically, e.g. by a command call in a VSCode extension. 

@theStiggySpd, we can add this to the description.

**Comment by tobiasqueck** [comment]
@Klaus-Keller @theStiggySpd thanks for the update acceptance criteria. It is clearer now.
Any plans for the future (or now) to also do the same or something similar for a system url when being in VSCode?

**Comment by theStiggySpd** [comment]
> @Klaus-Keller @theStiggySpd thanks for the update acceptance criteria. It is clearer now.
> Any plans for the future (or now) to also do the same or something similar for a system url when being in VSCode?

Hello @tobiasqueck That's correct. We do want to add some more relevant checks specific for SBAS and enable environment check for VSCode too. They will be added in subsequent feature requests after we have the first version of this new module out.
