### ISSUE TITLE
FEATURE - Typescript support for Fiori projects

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#621]
_As a **persona**,
I want to **develop UI5/Fiori applications using Typescript**,
so that I **make less mistakes thanks to the awesomeness of types**_

### Description
All writers should offer the option to generate source files either as JS or TS files. 

### Technical Design
1. `ui5-application-writer`: this is the most important one since it will contain all the required configurations
2. `fiori-freestyle-writer`: requires changes to all templates but should be relatively easy
3. `fiori-elements-writer`: needs the additional option to add TS support BUT should otherwise stay unchanged
4. `fe-fpm-writer`: requires changes to all templates but should be relatively easy 

On first glance, no other module should require a change.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have the interest to use Typescript
**when** I execute any of our writers with the typescript option set to true
**then** I will have a working TS project following best practice guidelines from https://github.com/ui5-community/ui5-ecosystem-showcase/pull/568

**Given** I have generated a TS project with the writers
**when** I execute any functionality with the SAP Fiori tools
**then** it will work without issues like in JS project.

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by tobiasqueck** [comment]
@petermuessig thank you for https://github.com/ui5-community/ui5-ecosystem-showcase/pull/568. We will be evaluating it and if it doesn't cause any problems with the SAP Fiori tools then we can move forward with adding TS support.

**Comment by petermuessig** [comment]
The `ui5-tooling-transpile` extensions have been released to npm:
https://www.npmjs.com/package/ui5-tooling-transpile

**Comment by tobiasqueck** [comment]
I have enhanced our `ui5-application-writer` and the `fiori-freestyle-writer` to support typescript at for the basic template in #626. Afterwards, I tested it with the Application Modeler extension in the SAP Fiori tools:
- App Info page worked without problems and I used it flawlessly to install the libs, add the spec (that is currently missing in the template) and open the preview 
- I also opened the page map and saw the correct application structure (after removing an incorrect entry in the manifest that was generated but that is an issue in my test case)
- when trying to enable FCL and add pages then things started breaking and I will investigate further

All in all, I am pretty happy with the first test results.
fyi: @ashleytung @petermuessig @Klaus-Keller

**Comment by tobiasqueck** [comment]
A 2nd PR is required after #629 is merged to address https://github.com/SAP/open-ux-tools/pull/626#pullrequestreview-1087170345.
