### ISSUE TITLE
BUG - `layeredRepository` service `isExistingVariant()` gives wrong output

### ISSUE THREAD

**Issue by testojs** [SAP/open-ux-tools#636]
### Related Feature
Feature request: #468

### Description
After deploying an adaptation project (app variant), the check for existing app variant with the same namespace returns 404, while it should return 200.

Here is a code snippet that checks if the app variant exists (it doesn't in the beginning), then deploys the variant and after that checks if the variant exists:

```javascript
import { createForAbap } from "@sap-ux/axios-extension";

const provider = createForAbap({ baseURL: "https://URZCLNT120.dest" });
const service = provider.layeredRepository();
try {
    let response = await service.isExistingVariant("apps/sap.ui.demoapps.rta.freestyle/appVariants/customer.adp.deploy.test.sample.project/");
    console.log("isExistingVariant", response.status);

    response = await service.deploy("./webapp.zip", {
        namespace: "apps/sap.ui.demoapps.rta.freestyle/appVariants/customer.adp.deploy.test.sample.project/",
        package: "ZUI_FLEX_TRANSPORT_TEST",
        transport: "URZK901109"
    });
    console.log("deploy:", response.status);

    response = await service.isExistingVariant("apps/sap.ui.demoapps.rta.freestyle/appVariants/customer.adp.deploy.test.sample.project/");
    console.log("isExistingVariant:", response.status);
    
} catch (error) {
    console.error("Error:", error.message);
}
// OUTPUT
// isExistingVariant:  404
// 2022-08-24 09:40:40 info    main: Success : Folder 'apps/sap.ui.demoapps.rta.freestyle/appVariants/customer.adp.deploy.test.sample.project/' (CUSTOMER_BASE) created in LRep. DTA deployed successfully (/UI5/DTA 010) 
// 2022-08-24 09:40:40 info    main: Information : File 'manifest' written into layer 'CUSTOMER_BASE' of the layered repository (/UI5/DTA 038) 
// 2022-08-24 09:40:40 info    main: Information : File 'i18n' written into layer 'CUSTOMER_BASE' of the layered repository (/UI5/DTA 038) 
// deploy:  200
// isExistingVariant:  404    ❗❗❗ wrong value, should be 200
```

After some time it begins to return the correct response (should be a caching issue).

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by testojs** [comment]
Here is the sample [webapp.zip](https://github.com/SAP/open-ux-tools/files/9415549/webapp.zip)

**Comment by tobiasqueck** [comment]
@testojs I started looking into but have trouble finding a system that I can use for debugging - I will reach out to you in a separate channel to get access to your landscape.
In the meantime in PR #637 I have enhanced our `examples/odata-cli` to be able to easily debug your scenario. It is an enhancement of your sample script allowing to test in BAS as well as locally.

**Comment by tobiasqueck** [comment]
The issue was indeed a caching issue. It seems the `/sap/bc/lrep` service is somehow caching the result of get requests for some time. To work around that 'feature', I am adding the timestamp as url parameter so that each request is has a unique query.
