### ISSUE TITLE
BUG - ui5-proxy-middleware does not work with UI5 library projects

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#693]
### Related Feature
Feature request: _issue number_

### Description
The `ui5-proxy-middleware` does not work with UI5 library projects because it tries to read the `minUI5Version` from `webapp/manifest.json` which does not exist in a standard library project.

### Steps to Reproduce
1. Install `easy-ui5` (and `yo`)
2. Generate a library project using `yo easy-ui5 library`
3. Add the `@sap-ux/ui5-proxy-middleware` as devDependency and ui5 dependency (in the package.json) and run `npm i`
4. Add the standard config to the `ui5.yaml`
5. Run `npm start`
6. See error

### Expected results
The preview starts without issues.

### Actual results
```
Error Message:
ENOENT: no such file or directory, open '/.../tmp/com.myorg.myUI5Library/webapp/manifest.json'
```

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
@zdravko-georgiev maybe something for you

**Comment by devinea** [comment]
@tobiasqueck Why would you preview the library like this? 
Normally I would expect an application to load the reuse lib using the static middleware form the workspace.

**Comment by tobiasqueck** [comment]
@devinea this is for developing a library. I wanted to use the `ui5-proxy-middleware` to test the code with different versions of UI5.
