### ISSUE TITLE
TBI - exclude pnpm-lock.yaml from prettier formatting

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#716]
### Description
To reduce conflicts and allow for easier comparison of changes in `dependencies` and `devDependencies`, we should consider excluding file [pnpm-lock.yaml](https://github.com/SAP/open-ux-tools/blob/main/pnpm-lock.yaml) from prettier formatting.
This could be achieved by adding the file to [.prettierignore](https://github.com/SAP/open-ux-tools/blob/main/.prettierignore).

### Value
- Less merge conflicts
- Simpler comparison of new or modified dependencies

### Architecture Elaboration
n/a

**Comment by tobiasqueck** [comment]
Fixed with #717
