### ISSUE TITLE
BUG - Unable to build or preview Fiori app when TS is enabled and using a namespace

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#761]
### Related Feature
Found when testing feature request https://github.com/SAP/open-ux-tools/issues/746

### Description
When generating a Typescript project using a module name of `myname` and namespace of `test.namespace`, the generated `app.id` causes the `npm run ts-typescheck` to fail. The `app.id` is a concatenation of the module name and namespace i.e. `myname.test.namespace`. The `ts-typecheck` command is run as part of the build and start commands which will now fail.

In `tsconfig.json` the path is added as `myname.test.namespace`
https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-application-writer/templates/optional/typescript/tsconfig.json#L17

However, the `componenent.ts` file is unable to find the associated module, https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/templates/basic/add/webapp/Component.ts#L2 since there is no mapping in the `tsconfig.json`.

### Steps to Reproduce
1. Start generating `SAPUI5 freestyle` app with `SAPUI5 Application` template
2. Select any available data source
3. On Project Attributes step, enter value for `Application namespace` - e.g. `test.<something>`
4. Set `Configure advanced options` to `Yes` and set `Enable TypeScript.` to `Yes`
5. You can also add deploy config selecting ABAP
6. Finish generation
7. Launch app preview with `npm start`

### Expected results
The Fiori app can be run in local preview mode or built without any exceptions.

### Actual results
TSC exception is thrown and prevents command from executing.

### Screenshots
![Screenshot 2022-10-25 at 17 05 59](https://user-images.githubusercontent.com/4520960/197827221-4ee09c01-0552-48a4-88ad-1bd45fd018c9.png)

#### Version/Components/Environment
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem}

### Fix
{describe the fix}

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by devinea** [comment]
@longieirl Thanks for the fix. I am closing as this seems to be complete. Please re-open if there is something remaining.
