### ISSUE TITLE
TBI - readonly states for input fields and dropdowns

### ISSUE THREAD

**Issue by gpeuc** [SAP/open-ux-tools#775]
We need a third state of input fields and various dropdowns - readonly. This is in addition to the current two: regular and disabled.

On the fundamental technical side, inputs just get `readonly` HTML property, and that's it.

But, there are some caveats:

1. We need to do special visual styling for readonly elements. Designs and variable definitions incoming.
2. Our dropdowns are "fake", they are an input field with lots of other constructs around them. Those should also go into readonly mode.
3. The readonly mode for our fancy dropdowns is as follows:

- input element is properly readonly
- the dropdown icon should stay there, but be _disabled_
- we should not be able to actually open the dropdown part 

4. The cursor should not change on hover, as that's how default HTML input works like. It should remain a standard arrow. This is in contrast to other enabled input fields where cursor goes into text-select mode.

- - - -

@815are @aislingnoone @tom-sap

**Comment by aislingnoone** [comment]
@colindoherty1 @ChristineMccarthy1 @richardmbyrnes

**Comment by colindoherty1** [comment]
Design for Read Only input fields 
![image](https://user-images.githubusercontent.com/52239744/200367542-13998ae3-81c1-47fa-8ccc-9a31d0ffcec6.png)

Readonly dropdowns with disabled arrow icons
![image](https://user-images.githubusercontent.com/52239744/200368137-0f32d404-bfdc-4c49-b230-adc5b86f49d6.png)


[Design in UI Kit](https://www.figma.com/file/tjmZpoyHzi61Rm1fm1gJ5u/Fiori-tools-UI-Kit?node-id=17%3A18905 )
