### ISSUE TITLE
BUG - Fiori Tools Page Editor freezes when changing the order of a custom column

### ISSUE THREAD

**Issue by jvanattedev** [SAP/open-ux-tools#800]
### Description
Starting from a simple Fiori Elements List Report application, consisting of several regular columns and one custom column, the Page Editor freezes when trying to change the order of the custom column using the provided up and down arrows in the page editor.

### Steps to Reproduce
1. Open the page editor for the List Report page
2. Open the Columns of the table on the Page Editor
3. Press the up arrow to change the order of the custom column in the table (so it moves to the left in the table)

### Expected results
The custom column should move to the left, in the Page Editor, and when running the application.
Perhaps if an invalid state has occured, some reason why this state occurred...

### Actual results
The page editor becomes unresponsive (freezes).

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
- Windows
- VS Code
- SAPUI5 v1.96.8
- "@sap/ux-ui5-tooling": "^1.8.0"
- "@ui5/cli": "^2.14.14"
- npm v8.19.2
- node v16.17.1

**Comment by tobiasqueck** [comment]
@jvanattedev that part of the functionality in the SAP Fiori tools, page modeler is not yet published here to the `open-ux-tools`, however, if you could provide the project causing the issues, I am sure we can try to help you.

**Comment by tobiasqueck** [comment]
@jvanattedev thanks for also reporting this as incident for the SAP Fiori tools. We are closing this one, and will be helping you in the incident.
