### ISSUE TITLE
TBI - Avoid duplicate custom views

### ISSUE THREAD

**Issue by stefanschreck** [SAP/open-ux-tools#837]
### Description (include screenshots)
The given implementation for the creation of custom views at the FPM writer allows adding a new custom view to the existing list of views in the manifest. 
Indeed, it is not checked if the new custom view is already registered. As a consequence, duplicate view entries get generated.

### Value
The enhancement is required due to a problem that we have with asynchronous execution of manifest changes from different sides: as a consequence, the custom view may or may not exist already. If it already exists, its default content shall get overwritten by the new values passed to the the FPM writer.

### Architecture Elaboration
There are two options how to solve this: either merge the new custom view into the list of all given views (`existingViews` at https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/view/index.ts), or to remove the old entry from this list if the key is found. 
The second option has the advantage that the template can stay as it is - but the significant disadvantage that the new view is appended at the end, and this changes the view order. Thus the first option is preferred.

### Tasks
- [ ] Task 1

**Comment by schreckstefan** [comment]
Solved by https://github.com/SAP/open-ux-tools/pull/838
