### ISSUE TITLE
BUG - fe-fpm-writer. controller-extension for TS application. Subsequent property declarations must have the same type.  Property 'base' must be of type '{ getExtensionAPI():

### ISSUE THREAD

**Issue by 815are** [SAP/open-ux-tools#841]
### Steps to Reproduce
1. Use ts application. For example - [project2-2022-12-160721.zip](https://github.com/SAP/open-ux-tools/files/10243513/project2-2022-12-160721.zip)
2. Generate two controller extension, but with different page types - 1st `ObjectPage` and 2nd `ListReport`

In result we have two ts controllers - `OP.controller.ts` and `LR.controller.ts`

In each `controller.ts` we have `declare module 'sap/ui/core/mvc/ControllerExtension'`, but return type for `getExtensionAPI()` differs:
1. `sap/fe/templates/ObjectPage/ExtensionAPI`
2. `sap/fe/templates/ListReport/ExtensionAPI`

Such state gives typescript error:
![image](https://user-images.githubusercontent.com/90789422/208045587-c0e99200-4265-4f8f-97e5-328105a717ed.png)

Attached app for reference - 
[project2-2022-12-160721.zip](https://github.com/SAP/open-ux-tools/files/10243513/project2-2022-12-160721.zip)

### Expected results
Generation of  `OP.controller.ts` and `LR.controller.ts` gives typescript error

### Actual results
Generation of  `OP.controller.ts` and `LR.controller.ts` without typescript errors

### Screenshots
![image](https://user-images.githubusercontent.com/90789422/208045587-c0e99200-4265-4f8f-97e5-328105a717ed.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [x] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
I think the easiest fix would be to use generics e.g. 
```
declare module 'sap/ui/core/mvc/ControllerExtension' {
    export default interface ControllerExtension<API> {
        base: {
            getExtensionAPI(): API;
        }
    }
}
```
And then 
```
export default ControllerExtension.extend('project2.ext.controller.LR', {
	override: {
		onInit(this: ControllerExtension<ExtensionAPI>) {
			// you can access the Fiori elements extensionAPI via this.base.getExtensionAPI
			const model = this.base.getExtensionAPI().getModel();
		}
	}
});
```

Since the generics part is the same for each controller, it might make sense to put it in a separate `ControllerExtension.d.ts` file and only generate it if it doesn't exist.

**Comment by tobiasqueck** [comment]
@815are, we could also go a little further an introduce class syntax for controller extensions. For your sample project, it would look like https://github.com/tobiasqueck/proposal-controller-extension/pull/2. Also for your reference, the previously suggested change is illustrated at https://github.com/tobiasqueck/proposal-controller-extension/pull/1

**Comment by tobiasqueck** [comment]
@815are @devinea what do you think? Should we go for https://github.com/tobiasqueck/proposal-controller-extension/pull/2? It finally gets also nice class syntax for controller extensions?

**Comment by 815are** [comment]
> @815are @devinea what do you think? Should we go for [tobiasqueck/proposal-controller-extension#2](https://github.com/tobiasqueck/proposal-controller-extension/pull/2)? It finally gets also nice class syntax for controller extensions?

@tobiasqueck 
I think 2nd looks nicer, but in 2nd approach I see other changes made in `babelrc`, `ui5-local.yaml`. If we choice 2nd solution then app generator should apply those changes or it is optional?

**Comment by tobiasqueck** [comment]
@815are, yes, this would also require changes in the `ui5-application-writer` i.e. increment the version of the transpile tooling and add a `.babelrc`. However, these changes would come anyhow since it allows to have one config for all transpile middleware and tasks in all `ui5*.yaml` files.

**Comment by 815are** [comment]
@tobiasqueck 

Probably another argument for 2nd solution is that we have such syntax for Custom Page controller - https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/templates/page/custom/1.94/ext/Controller.ts#L6

I would vote for 2nd approach

**Comment by devinea** [comment]
> @815are @devinea what do you think? Should we go for [tobiasqueck/proposal-controller-extension#2](https://github.com/tobiasqueck/proposal-controller-extension/pull/2)? It finally gets also nice class syntax for controller extensions?

I don't have a strong opinion on this. Option 2 looks fine.

**Comment by tobiasqueck** [comment]
@815are how urgent is this one for you? I won't be able to look into it before next year. If you need it earlier, you can go for it, and I do a review, otherwise, it needs to wait.

**Comment by 815are** [comment]
> @815are how urgent is this one for you? I won't be able to look into it before next year. If you need it earlier, you can go for it, and I do a review, otherwise, it needs to wait.

@tobiasqueck 
It is not urgent. I will keep in mind and also can apply change

**Comment by 815are** [comment]
PR with applying proposed [solution 2](https://github.com/tobiasqueck/proposal-controller-extension/pull/2) - https://github.com/SAP/open-ux-tools/pull/858
