### ISSUE TITLE
BUG - fiori deploy error message contains typo

### ISSUE THREAD

**Issue by tobiashofmann** [SAP/open-ux-tools#842]
### Description

I am deploying an application to my on-premise Gateway System. The deploy fails (which is OK and not the actual problem) and the error text I get shows (in German):

ERR! builder:custom deploy-to-abap SAPUI5-Anwendung Z... wurde nicht erfolgerich hochgeladen oder registriert

The error text contains a typo: erfolgerich

Not sure if this message comes as-is from the backend or from the fiori tools. Using for erfolgerich via grep did not show anything.

### Steps to Reproduce

1. Have a UI5 build that cannot be deployed, e.g. invalid file type
2. Build the app
3. Deploy to on premise SAP Getway (7.52 SP10) with a user configured for German language
4. Deploy fails and shows error message with type

### Expected results

erfolgreich 

### Actual results

erfolgerich 

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [X] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by devinea** [comment]
@tobiashofmann Fiori tools is currently only available in English the German comes from the backend user setting.
FYI If you prefer to also use English during deployment this can be configured as shown here https://help.sap.com/docs/SAP_FIORI_tools/17d50220bcd848aa854c9c182d65b699/c06b9cbb3f3641aabfe3a5d199e855a0.html#example-configuration---additional-params 
I'll close this as the German text comes from the backend server. Logging a customer issue would be better for that.

**Comment by silkearians** [comment]
@tobiashofmann thanks a lot for mentioning the typo in German translation. We immediately have informed our German translation team at SAP to correct it in the backend which they did now
