### ISSUE TITLE
TBI - TS - Add local type definition for Fiori Elements V2 on UI5 version less than 1.109.1

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#844]
### Description (include screenshots)
What will this TBI achieve, and how will it be measured as done. Is it documentation, increase of test coverage, refactoring

TBI - TS - Add local type definition for Fiori Elements V2 on UI5 version less than 1.109.1 as the type definition is not available in lower versions of ui5. 

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by tobiasqueck** [comment]
@devinea looks to me like it is done, so I am closing it, please reopen and explain what is missing if I was wrong.
