### ISSUE TITLE
FEATURE - Support query available package names using ADT service

### ISSUE THREAD

**Issue by slin-sap** [SAP/open-ux-tools#887]
As a consumer of axios-extension library,
I want to support ADT service that queries list of available package names,
so that I can call this API to show list of package names in Fiori deployment configuration tool.

### Technical Design
Same implementation approach as other ADT services that have been implemented in axios-extensions.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a ABAP onprem system with ADT service enabled
**when** I call listPackages API
**then** A list of package names are returned by ABAP ADT service

### Tasks
- [x] Implementation
- [x] Unit Tests added
- [x] odata-cli example is updated with test case to load list of packages.

**Comment by tobiasqueck** [comment]
@slin-sap this seems to be done, so I am closing it, if that is wrong, please reopen.
