### ISSUE TITLE
BUG - logic for finding a service needs to be enhanced

### ISSUE THREAD

**Issue by zdravko-georgiev** [SAP/open-ux-tools#924]
### Description
The existing logic
https://github.com/SAP/open-ux-tools/blob/23ff77e63d288932a4fc26ade39115b2ac75a20f/packages/axios-extension/src/abap/catalog/v2-catalog-service.ts#L93-L106

needs to be enhanced, because it doesn't consider that a service URI can contain also segment parameters, e.g. `path/to/backend/SERVICENAME;v=0001/`, where `v` stands for version. If such path is passed to the `findService` method, then the logic inside will derive `SERVICENAME;v=0001` as service title, which is wrong.

Additionally when searching for a service it is better to include also the service version in the query, for the case when they are multiple service versions.

### Expected results
Correct filter parameters are used when searching for a service

### Actual results
Wrong filter parameters used when searching for a service

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by zdravko-georgiev** [comment]
FYI: Information about segment parameter https://www.ietf.org/rfc/rfc2396.txt section 3.3

**Comment by tobiasqueck** [comment]
@zdravko-georgiev it looks to me like #925 is fixing this issue, so I am closing it. Please reopen and explain what is missing if I was wrong.
