### ISSUE TITLE
BUG - FLP Embedded preview fails to load

### ISSUE THREAD

**Issue by johannes-kolbe** [SAP/open-ux-tools#937]
Issue: tools-suite #23945

Adding a FLP Embedded Configuration to an application and starting preview might lead to an error 
`Page load fails with net::ERR_CONTENT_DECODING_FAILED 200` with preview not loading.

**Comment by johannes-kolbe** [comment]
Hi @tobiasqueck, we are encountering an issue with setting the `accept-encoding` header to `br` ([backend-proxy-middleware](https://github.com/SAP/open-ux-tools/blob/main/packages/backend-proxy-middleware/src/base/proxy.ts#L43)) for an application. Would you know if that is still always required?

**Comment by shahzeb79** [comment]
@johannes-kolbe Thanks alot for raising it. Just to clarify, its issue with our all fiori apps trying to load launchpad in embedded mode.

**Comment by tobiasqueck** [comment]
> Hi @tobiasqueck, we are encountering an issue with setting the `accept-encoding` header to `br` ([backend-proxy-middleware](https://github.com/SAP/open-ux-tools/blob/main/packages/backend-proxy-middleware/src/base/proxy.ts#L43)) for an application. Would you know if that is still always required?

I don't understand the question.

**Comment by johannes-kolbe** [comment]
> I don't understand the question.

@tobiasqueck Sorry about the formulation, and please feel free to redirect me. 
The question (also being investigated on tools-suite issue) is if the special setting of `accept-encoding` to `br` is still necessary in case of flp embedded preview for `Fiorilaunchpad.html`. It seems like something changed in that case.
I naively saw your name with the code here, but I assume this was related to the move from tools-suite. 🙂

**Comment by tobiasqueck** [comment]
@johannes-kolbe thanks for the explanation. You are correct, I move some code there but the brain behind that one is @zdravko-georgiev

**Comment by johannes-kolbe** [comment]
Fix applied in PR #944, consumption and final verification will happen on tools-suite side. Closing issue.
