### ISSUE TITLE
TBI - Proposal to increase robustness of environment check

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#945]
### Description
Module [`@sap-ux/environment-check`](https://github.com/SAP/open-ux-tools/tree/main/packages/environment-check) helps analyzing issues when developing SAP Fiori applications by checking the current environment. Main focus is here on connectivity of destinations in  SAP Business Application Studio (BAS) or saved systems in Microsoft Visual Studio Code. 

In a BAS environment we experienced situations, where the destination to be checked is not listed and recognized by the environment check tool. Root cause are filter conditions in used module `@sap/bas-sdk`, which follows a more restrictive approach, meaning new types of destinations need to be allowed-listed. This causes issues with the usability of `@sap-ux/environment-check`.

Proposal is, to use plain HTTP requests to retrieve the list of destinations over 

### Value
Better and more robust analyzation of destination issues.

### Architecture Elaboration
Replace
https://github.com/SAP/open-ux-tools/blob/74222f04ec0e003519beb3b09be5f536bfbfc819/packages/environment-check/src/checks/destination.ts#L92
with plain HTTP request `$H2O_URL/api/listDestinations` to retrieve list of destinations.

**Comment by tobiasqueck** [comment]
@Klaus-Keller could you please replace it with a call to https://github.com/SAP/open-ux-tools/blob/74222f04ec0e003519beb3b09be5f536bfbfc819/packages/btp-utils/src/app-studio.ts#L75. It does the same but at least keeps the app-studio specific knowledge in one place.

**Comment by cianmSAP** [comment]
Closing as `sap-ux/btp-utils` is now used for retrieving destinations
