### ISSUE TITLE
TBI - Export fileExists function

### ISSUE THREAD

**Issue by korotkovao** [SAP/open-ux-tools#962]
### Description (include screenshots)
Export `fileExists` function in `project-access/src/file/file-access.ts` to be consumed in other modules in the future.

### Value
Avoids code duplication and prevents future maintenance.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by tobiasqueck** [comment]
@korotkovao this is a bit too abstract. Could you please outline your specific use case that you are working on right now that requires the exposure of the function? Additionally, you are proposing to change an API, so it is not a TBI anymore but a feature request.

**Comment by korotkovao** [comment]
Closing this issue as there was [previously a decision against it](https://github.com/SAP/open-ux-tools/pull/963#pullrequestreview-1359811723)

> we initially thought about whether or not to make the [file access functions](https://github.com/SAP/open-ux-tools/blob/main/packages/project-access/src/file/file-access.ts) public available. Eventually, we've decided against it: The functions provide low level file access, which can be easily achieved using functions from built-in module fs. However, we've also added support mem-fs editor, so you can pass an instance of Editor which then will be also use to do file operations (e.g. a file exists in mem-fs only). If it's the mem-fs capabilities you are looking to use we could consider to add these functions to public interface.
