### ISSUE TITLE
BUG - Sonar: Unsafe usage of optional chaining

### ISSUE THREAD

**Issue by kranthie-sap** [SAP/open-ux-tools#973]
### Description
The following bugs with 'major' priority are reported in sonar cloud `Unsafe usage of optional chaining. If it short-circuits with 'undefined' the evaluation will throw TypeError.`:
* [packages/axios-extension/src/auth/connection.ts](https://sonarcloud.io/code?id=SAP_open-ux-tools&selected=SAP_open-ux-tools%3Apackages%2Faxios-extension%2Fsrc%2Fauth%2Fconnection.ts&line=39)
* [packages/app-config-writer/src/smartlinks-config/ui5-yaml.ts](https://sonarcloud.io/code?id=SAP_open-ux-tools&selected=SAP_open-ux-tools%3Apackages%2Fapp-config-writer%2Fsrc%2Fsmartlinks-config%2Fui5-yaml.ts&line=29)

### Why is this an issue?
<img width="1001" alt="Screenshot 2023-04-04 at 09 01 24" src="https://user-images.githubusercontent.com/84985584/229850727-f901e18e-0bed-4ad3-b1ee-17fc2f9dfd07.png">

### How to fix the issue?
<img width="995" alt="Screenshot 2023-04-04 at 09 01 32" src="https://user-images.githubusercontent.com/84985584/229850746-dadc1c63-734e-4e4a-8701-896fa21e4dc9.png">

**Comment by tobiasqueck** [comment]
@kranthie-sap it looks to me like this fixed with #974 so I am closing it. If it is still an issue then please reopen and explain what is missing.
